#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 17
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 1
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 2

enum {
  sym_word = 1,
  sym_line_break = 2,
  anon_sym_PLUS = 3,
  anon_sym_GT = 4,
  anon_sym_GT_GT = 5,
  anon_sym_GT_GT_GT = 6,
  anon_sym_GT_GT_GT_GT = 7,
  anon_sym_GT_GT_GT_GT_GT = 8,
  anon_sym_GT_GT_GT_GT_GT_GT = 9,
  sym_document = 10,
  sym_carryover_tag = 11,
  sym_quote = 12,
  sym_quote1 = 13,
  sym_quote2 = 14,
  sym_quote3 = 15,
  sym_quote4 = 16,
  sym_quote5 = 17,
  sym_quote6 = 18,
  aux_sym_document_repeat1 = 19,
  aux_sym_quote_repeat1 = 20,
  aux_sym_quote1_repeat1 = 21,
  aux_sym_quote1_repeat2 = 22,
  aux_sym_quote2_repeat1 = 23,
  aux_sym_quote3_repeat1 = 24,
  aux_sym_quote4_repeat1 = 25,
  aux_sym_quote5_repeat1 = 26,
  aux_sym_quote6_repeat1 = 27,
  anon_alias_sym__word = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_word] = "tag_name",
  [sym_line_break] = "_line_break",
  [anon_sym_PLUS] = "+",
  [anon_sym_GT] = "> ",
  [anon_sym_GT_GT] = ">> ",
  [anon_sym_GT_GT_GT] = ">>> ",
  [anon_sym_GT_GT_GT_GT] = ">>>> ",
  [anon_sym_GT_GT_GT_GT_GT] = ">>>>> ",
  [anon_sym_GT_GT_GT_GT_GT_GT] = ">>>>>> ",
  [sym_document] = "document",
  [sym_carryover_tag] = "carryover_tag",
  [sym_quote] = "quote",
  [sym_quote1] = "quote1",
  [sym_quote2] = "quote2",
  [sym_quote3] = "quote3",
  [sym_quote4] = "quote4",
  [sym_quote5] = "quote5",
  [sym_quote6] = "quote6",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_quote_repeat1] = "quote_repeat1",
  [aux_sym_quote1_repeat1] = "quote1_repeat1",
  [aux_sym_quote1_repeat2] = "quote1_repeat2",
  [aux_sym_quote2_repeat1] = "quote2_repeat1",
  [aux_sym_quote3_repeat1] = "quote3_repeat1",
  [aux_sym_quote4_repeat1] = "quote4_repeat1",
  [aux_sym_quote5_repeat1] = "quote5_repeat1",
  [aux_sym_quote6_repeat1] = "quote6_repeat1",
  [anon_alias_sym__word] = "_word",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_word] = sym_word,
  [sym_line_break] = sym_line_break,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_GT_GT_GT] = anon_sym_GT_GT_GT,
  [anon_sym_GT_GT_GT_GT] = anon_sym_GT_GT_GT_GT,
  [anon_sym_GT_GT_GT_GT_GT] = anon_sym_GT_GT_GT_GT_GT,
  [anon_sym_GT_GT_GT_GT_GT_GT] = anon_sym_GT_GT_GT_GT_GT_GT,
  [sym_document] = sym_document,
  [sym_carryover_tag] = sym_carryover_tag,
  [sym_quote] = sym_quote,
  [sym_quote1] = sym_quote1,
  [sym_quote2] = sym_quote2,
  [sym_quote3] = sym_quote3,
  [sym_quote4] = sym_quote4,
  [sym_quote5] = sym_quote5,
  [sym_quote6] = sym_quote6,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_quote_repeat1] = aux_sym_quote_repeat1,
  [aux_sym_quote1_repeat1] = aux_sym_quote1_repeat1,
  [aux_sym_quote1_repeat2] = aux_sym_quote1_repeat2,
  [aux_sym_quote2_repeat1] = aux_sym_quote2_repeat1,
  [aux_sym_quote3_repeat1] = aux_sym_quote3_repeat1,
  [aux_sym_quote4_repeat1] = aux_sym_quote4_repeat1,
  [aux_sym_quote5_repeat1] = aux_sym_quote5_repeat1,
  [aux_sym_quote6_repeat1] = aux_sym_quote6_repeat1,
  [anon_alias_sym__word] = anon_alias_sym__word,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = false,
  },
  [sym_line_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_GT_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_carryover_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_quote1] = {
    .visible = true,
    .named = true,
  },
  [sym_quote2] = {
    .visible = true,
    .named = true,
  },
  [sym_quote3] = {
    .visible = true,
    .named = true,
  },
  [sym_quote4] = {
    .visible = true,
    .named = true,
  },
  [sym_quote5] = {
    .visible = true,
    .named = true,
  },
  [sym_quote6] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote1_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote1_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote2_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote3_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote4_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote5_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote6_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym__word] = {
    .visible = true,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = anon_alias_sym__word,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '+') ADVANCE(12);
      if (lookahead == '>') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == '>') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(14);
      if (lookahead == '>') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(15);
      if (lookahead == '>') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(16);
      if (lookahead == '>') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '>') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_line_break);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT_GT_GT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT_GT_GT_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_line_break] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_GT_GT_GT] = ACTIONS(1),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(1),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(1),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(57),
    [sym_carryover_tag] = STATE(39),
    [sym_quote] = STATE(5),
    [sym_quote1] = STATE(8),
    [sym_quote2] = STATE(8),
    [sym_quote3] = STATE(8),
    [sym_quote4] = STATE(8),
    [sym_quote5] = STATE(8),
    [sym_quote6] = STATE(8),
    [aux_sym_document_repeat1] = STATE(5),
    [aux_sym_quote_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_GT_GT] = ACTIONS(9),
    [anon_sym_GT_GT_GT] = ACTIONS(11),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(13),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(15),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(17),
  },
  [2] = {
    [sym_carryover_tag] = STATE(40),
    [sym_quote2] = STATE(16),
    [sym_quote3] = STATE(16),
    [sym_quote4] = STATE(16),
    [sym_quote5] = STATE(16),
    [sym_quote6] = STATE(16),
    [aux_sym_quote1_repeat1] = STATE(31),
    [aux_sym_quote1_repeat2] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_word] = ACTIONS(21),
    [sym_line_break] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(28),
    [anon_sym_GT_GT_GT] = ACTIONS(31),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(34),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(37),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(40),
  },
  [3] = {
    [sym_carryover_tag] = STATE(39),
    [sym_quote] = STATE(3),
    [sym_quote1] = STATE(8),
    [sym_quote2] = STATE(8),
    [sym_quote3] = STATE(8),
    [sym_quote4] = STATE(8),
    [sym_quote5] = STATE(8),
    [sym_quote6] = STATE(8),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_quote_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(48),
    [anon_sym_GT_GT] = ACTIONS(51),
    [anon_sym_GT_GT_GT] = ACTIONS(54),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(57),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(60),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(63),
  },
  [4] = {
    [sym_carryover_tag] = STATE(40),
    [sym_quote2] = STATE(15),
    [sym_quote3] = STATE(15),
    [sym_quote4] = STATE(15),
    [sym_quote5] = STATE(15),
    [sym_quote6] = STATE(15),
    [aux_sym_quote1_repeat1] = STATE(31),
    [aux_sym_quote1_repeat2] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(66),
    [sym_word] = ACTIONS(21),
    [sym_line_break] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(68),
    [anon_sym_GT] = ACTIONS(66),
    [anon_sym_GT_GT] = ACTIONS(71),
    [anon_sym_GT_GT_GT] = ACTIONS(74),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(77),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(80),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(83),
  },
  [5] = {
    [sym_carryover_tag] = STATE(39),
    [sym_quote] = STATE(3),
    [sym_quote1] = STATE(8),
    [sym_quote2] = STATE(8),
    [sym_quote3] = STATE(8),
    [sym_quote4] = STATE(8),
    [sym_quote5] = STATE(8),
    [sym_quote6] = STATE(8),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_quote_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(86),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_GT_GT] = ACTIONS(9),
    [anon_sym_GT_GT_GT] = ACTIONS(11),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(13),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(15),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(17),
  },
  [6] = {
    [sym_carryover_tag] = STATE(41),
    [sym_quote3] = STATE(21),
    [sym_quote4] = STATE(21),
    [sym_quote5] = STATE(21),
    [sym_quote6] = STATE(21),
    [aux_sym_quote1_repeat1] = STATE(31),
    [aux_sym_quote2_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(88),
    [sym_word] = ACTIONS(21),
    [sym_line_break] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(90),
    [anon_sym_GT] = ACTIONS(88),
    [anon_sym_GT_GT] = ACTIONS(88),
    [anon_sym_GT_GT_GT] = ACTIONS(93),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(96),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(99),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(102),
  },
  [7] = {
    [sym_carryover_tag] = STATE(41),
    [sym_quote3] = STATE(19),
    [sym_quote4] = STATE(19),
    [sym_quote5] = STATE(19),
    [sym_quote6] = STATE(19),
    [aux_sym_quote1_repeat1] = STATE(31),
    [aux_sym_quote2_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(105),
    [sym_word] = ACTIONS(21),
    [sym_line_break] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(107),
    [anon_sym_GT] = ACTIONS(105),
    [anon_sym_GT_GT] = ACTIONS(105),
    [anon_sym_GT_GT_GT] = ACTIONS(110),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(113),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(116),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(119),
  },
  [8] = {
    [sym_carryover_tag] = STATE(39),
    [sym_quote1] = STATE(10),
    [sym_quote2] = STATE(10),
    [sym_quote3] = STATE(10),
    [sym_quote4] = STATE(10),
    [sym_quote5] = STATE(10),
    [sym_quote6] = STATE(10),
    [aux_sym_quote_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(122),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_GT_GT] = ACTIONS(9),
    [anon_sym_GT_GT_GT] = ACTIONS(11),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(13),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(15),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(17),
  },
  [9] = {
    [sym_carryover_tag] = STATE(47),
    [sym_quote4] = STATE(24),
    [sym_quote5] = STATE(24),
    [sym_quote6] = STATE(24),
    [aux_sym_quote1_repeat1] = STATE(31),
    [aux_sym_quote3_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(124),
    [sym_word] = ACTIONS(21),
    [sym_line_break] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(126),
    [anon_sym_GT] = ACTIONS(124),
    [anon_sym_GT_GT] = ACTIONS(124),
    [anon_sym_GT_GT_GT] = ACTIONS(124),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(129),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(132),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(135),
  },
  [10] = {
    [sym_carryover_tag] = STATE(39),
    [sym_quote1] = STATE(10),
    [sym_quote2] = STATE(10),
    [sym_quote3] = STATE(10),
    [sym_quote4] = STATE(10),
    [sym_quote5] = STATE(10),
    [sym_quote6] = STATE(10),
    [aux_sym_quote_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(138),
    [anon_sym_PLUS] = ACTIONS(140),
    [anon_sym_GT] = ACTIONS(143),
    [anon_sym_GT_GT] = ACTIONS(146),
    [anon_sym_GT_GT_GT] = ACTIONS(149),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(152),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(155),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(158),
  },
  [11] = {
    [sym_carryover_tag] = STATE(47),
    [sym_quote4] = STATE(23),
    [sym_quote5] = STATE(23),
    [sym_quote6] = STATE(23),
    [aux_sym_quote1_repeat1] = STATE(31),
    [aux_sym_quote3_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(161),
    [sym_word] = ACTIONS(21),
    [sym_line_break] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(163),
    [anon_sym_GT] = ACTIONS(161),
    [anon_sym_GT_GT] = ACTIONS(161),
    [anon_sym_GT_GT_GT] = ACTIONS(161),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(166),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(169),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(172),
  },
  [12] = {
    [sym_carryover_tag] = STATE(55),
    [sym_quote5] = STATE(27),
    [sym_quote6] = STATE(27),
    [aux_sym_quote1_repeat1] = STATE(31),
    [aux_sym_quote4_repeat1] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(175),
    [sym_word] = ACTIONS(21),
    [sym_line_break] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(177),
    [anon_sym_GT] = ACTIONS(175),
    [anon_sym_GT_GT] = ACTIONS(175),
    [anon_sym_GT_GT_GT] = ACTIONS(175),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(175),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(180),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(183),
  },
  [13] = {
    [sym_carryover_tag] = STATE(55),
    [sym_quote5] = STATE(28),
    [sym_quote6] = STATE(28),
    [aux_sym_quote1_repeat1] = STATE(31),
    [aux_sym_quote4_repeat1] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(186),
    [sym_word] = ACTIONS(21),
    [sym_line_break] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(188),
    [anon_sym_GT] = ACTIONS(186),
    [anon_sym_GT_GT] = ACTIONS(186),
    [anon_sym_GT_GT_GT] = ACTIONS(186),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(186),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(191),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(194),
  },
  [14] = {
    [sym_carryover_tag] = STATE(40),
    [sym_quote2] = STATE(14),
    [sym_quote3] = STATE(14),
    [sym_quote4] = STATE(14),
    [sym_quote5] = STATE(14),
    [sym_quote6] = STATE(14),
    [aux_sym_quote1_repeat2] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(197),
    [anon_sym_PLUS] = ACTIONS(199),
    [anon_sym_GT] = ACTIONS(197),
    [anon_sym_GT_GT] = ACTIONS(202),
    [anon_sym_GT_GT_GT] = ACTIONS(205),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(208),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(211),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(214),
  },
  [15] = {
    [sym_carryover_tag] = STATE(40),
    [sym_quote2] = STATE(14),
    [sym_quote3] = STATE(14),
    [sym_quote4] = STATE(14),
    [sym_quote5] = STATE(14),
    [sym_quote6] = STATE(14),
    [aux_sym_quote1_repeat2] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(28),
    [anon_sym_GT_GT_GT] = ACTIONS(31),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(34),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(37),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(40),
  },
  [16] = {
    [sym_carryover_tag] = STATE(40),
    [sym_quote2] = STATE(14),
    [sym_quote3] = STATE(14),
    [sym_quote4] = STATE(14),
    [sym_quote5] = STATE(14),
    [sym_quote6] = STATE(14),
    [aux_sym_quote1_repeat2] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(217),
    [anon_sym_PLUS] = ACTIONS(219),
    [anon_sym_GT] = ACTIONS(217),
    [anon_sym_GT_GT] = ACTIONS(222),
    [anon_sym_GT_GT_GT] = ACTIONS(225),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(228),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(231),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(234),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(23), 1,
      sym_line_break,
    ACTIONS(239), 1,
      anon_sym_PLUS,
    ACTIONS(242), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(31), 1,
      aux_sym_quote1_repeat1,
    STATE(56), 1,
      sym_carryover_tag,
    STATE(32), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(237), 6,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
  [31] = 8,
    ACTIONS(247), 1,
      anon_sym_PLUS,
    ACTIONS(250), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(253), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(256), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(259), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(41), 1,
      sym_carryover_tag,
    ACTIONS(245), 3,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
    STATE(18), 5,
      sym_quote3,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote2_repeat1,
  [62] = 8,
    ACTIONS(90), 1,
      anon_sym_PLUS,
    ACTIONS(93), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(96), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(99), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(102), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(41), 1,
      sym_carryover_tag,
    ACTIONS(88), 3,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
    STATE(18), 5,
      sym_quote3,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote2_repeat1,
  [93] = 8,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(23), 1,
      sym_line_break,
    ACTIONS(264), 1,
      anon_sym_PLUS,
    ACTIONS(267), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(31), 1,
      aux_sym_quote1_repeat1,
    STATE(56), 1,
      sym_carryover_tag,
    STATE(33), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(262), 6,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
  [124] = 8,
    ACTIONS(272), 1,
      anon_sym_PLUS,
    ACTIONS(275), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(278), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(281), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(284), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(41), 1,
      sym_carryover_tag,
    ACTIONS(270), 3,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
    STATE(18), 5,
      sym_quote3,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote2_repeat1,
  [155] = 7,
    ACTIONS(289), 1,
      anon_sym_PLUS,
    ACTIONS(292), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(295), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(298), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(47), 1,
      sym_carryover_tag,
    ACTIONS(287), 4,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
    STATE(22), 4,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote3_repeat1,
  [183] = 7,
    ACTIONS(126), 1,
      anon_sym_PLUS,
    ACTIONS(129), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(132), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(135), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(47), 1,
      sym_carryover_tag,
    ACTIONS(124), 4,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
    STATE(22), 4,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote3_repeat1,
  [211] = 7,
    ACTIONS(303), 1,
      anon_sym_PLUS,
    ACTIONS(306), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(309), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(312), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(47), 1,
      sym_carryover_tag,
    ACTIONS(301), 4,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
    STATE(22), 4,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote3_repeat1,
  [239] = 5,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(23), 1,
      sym_line_break,
    STATE(31), 1,
      aux_sym_quote1_repeat1,
    STATE(37), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(315), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [262] = 6,
    ACTIONS(319), 1,
      anon_sym_PLUS,
    ACTIONS(322), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(325), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(55), 1,
      sym_carryover_tag,
    STATE(26), 3,
      sym_quote5,
      sym_quote6,
      aux_sym_quote4_repeat1,
    ACTIONS(317), 5,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
  [287] = 6,
    ACTIONS(330), 1,
      anon_sym_PLUS,
    ACTIONS(333), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(336), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(55), 1,
      sym_carryover_tag,
    STATE(26), 3,
      sym_quote5,
      sym_quote6,
      aux_sym_quote4_repeat1,
    ACTIONS(328), 5,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
  [312] = 6,
    ACTIONS(177), 1,
      anon_sym_PLUS,
    ACTIONS(180), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(183), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(55), 1,
      sym_carryover_tag,
    STATE(26), 3,
      sym_quote5,
      sym_quote6,
      aux_sym_quote4_repeat1,
    ACTIONS(175), 5,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
  [337] = 5,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(23), 1,
      sym_line_break,
    STATE(31), 1,
      aux_sym_quote1_repeat1,
    STATE(35), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(339), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [360] = 5,
    ACTIONS(343), 1,
      anon_sym_PLUS,
    ACTIONS(346), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(56), 1,
      sym_carryover_tag,
    STATE(30), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(341), 6,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
  [382] = 4,
    ACTIONS(351), 1,
      sym_word,
    ACTIONS(354), 1,
      sym_line_break,
    STATE(31), 1,
      aux_sym_quote1_repeat1,
    ACTIONS(349), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [402] = 5,
    ACTIONS(359), 1,
      anon_sym_PLUS,
    ACTIONS(362), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(56), 1,
      sym_carryover_tag,
    STATE(30), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(357), 6,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
  [424] = 5,
    ACTIONS(239), 1,
      anon_sym_PLUS,
    ACTIONS(242), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(56), 1,
      sym_carryover_tag,
    STATE(30), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(237), 6,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
  [446] = 2,
    ACTIONS(367), 1,
      sym_word,
    ACTIONS(365), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [461] = 2,
    STATE(36), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(369), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [475] = 2,
    STATE(36), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(371), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [489] = 2,
    STATE(36), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(339), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [503] = 1,
    ACTIONS(373), 6,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [512] = 6,
    ACTIONS(375), 1,
      anon_sym_GT,
    ACTIONS(377), 1,
      anon_sym_GT_GT,
    ACTIONS(379), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(381), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(383), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(385), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [531] = 5,
    ACTIONS(377), 1,
      anon_sym_GT_GT,
    ACTIONS(379), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(381), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(383), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(385), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [547] = 4,
    ACTIONS(379), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(381), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(383), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(385), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [560] = 3,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(387), 1,
      sym_line_break,
    STATE(12), 1,
      aux_sym_quote1_repeat1,
  [570] = 3,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(389), 1,
      sym_line_break,
    STATE(11), 1,
      aux_sym_quote1_repeat1,
  [580] = 3,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(391), 1,
      sym_line_break,
    STATE(7), 1,
      aux_sym_quote1_repeat1,
  [590] = 3,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(393), 1,
      sym_line_break,
    STATE(4), 1,
      aux_sym_quote1_repeat1,
  [600] = 3,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(395), 1,
      sym_line_break,
    STATE(13), 1,
      aux_sym_quote1_repeat1,
  [610] = 3,
    ACTIONS(381), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(383), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(385), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [620] = 3,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(397), 1,
      sym_line_break,
    STATE(20), 1,
      aux_sym_quote1_repeat1,
  [630] = 3,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(399), 1,
      sym_line_break,
    STATE(29), 1,
      aux_sym_quote1_repeat1,
  [640] = 3,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(401), 1,
      sym_line_break,
    STATE(17), 1,
      aux_sym_quote1_repeat1,
  [650] = 3,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(403), 1,
      sym_line_break,
    STATE(25), 1,
      aux_sym_quote1_repeat1,
  [660] = 3,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(405), 1,
      sym_line_break,
    STATE(9), 1,
      aux_sym_quote1_repeat1,
  [670] = 3,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(407), 1,
      sym_line_break,
    STATE(6), 1,
      aux_sym_quote1_repeat1,
  [680] = 3,
    ACTIONS(21), 1,
      sym_word,
    ACTIONS(409), 1,
      sym_line_break,
    STATE(2), 1,
      aux_sym_quote1_repeat1,
  [690] = 2,
    ACTIONS(383), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(385), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [697] = 1,
    ACTIONS(385), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [701] = 1,
    ACTIONS(411), 1,
      ts_builtin_sym_end,
  [705] = 1,
    ACTIONS(413), 1,
      sym_word,
  [709] = 1,
    ACTIONS(415), 1,
      sym_line_break,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(17)] = 0,
  [SMALL_STATE(18)] = 31,
  [SMALL_STATE(19)] = 62,
  [SMALL_STATE(20)] = 93,
  [SMALL_STATE(21)] = 124,
  [SMALL_STATE(22)] = 155,
  [SMALL_STATE(23)] = 183,
  [SMALL_STATE(24)] = 211,
  [SMALL_STATE(25)] = 239,
  [SMALL_STATE(26)] = 262,
  [SMALL_STATE(27)] = 287,
  [SMALL_STATE(28)] = 312,
  [SMALL_STATE(29)] = 337,
  [SMALL_STATE(30)] = 360,
  [SMALL_STATE(31)] = 382,
  [SMALL_STATE(32)] = 402,
  [SMALL_STATE(33)] = 424,
  [SMALL_STATE(34)] = 446,
  [SMALL_STATE(35)] = 461,
  [SMALL_STATE(36)] = 475,
  [SMALL_STATE(37)] = 489,
  [SMALL_STATE(38)] = 503,
  [SMALL_STATE(39)] = 512,
  [SMALL_STATE(40)] = 531,
  [SMALL_STATE(41)] = 547,
  [SMALL_STATE(42)] = 560,
  [SMALL_STATE(43)] = 570,
  [SMALL_STATE(44)] = 580,
  [SMALL_STATE(45)] = 590,
  [SMALL_STATE(46)] = 600,
  [SMALL_STATE(47)] = 610,
  [SMALL_STATE(48)] = 620,
  [SMALL_STATE(49)] = 630,
  [SMALL_STATE(50)] = 640,
  [SMALL_STATE(51)] = 650,
  [SMALL_STATE(52)] = 660,
  [SMALL_STATE(53)] = 670,
  [SMALL_STATE(54)] = 680,
  [SMALL_STATE(55)] = 690,
  [SMALL_STATE(56)] = 697,
  [SMALL_STATE(57)] = 701,
  [SMALL_STATE(58)] = 705,
  [SMALL_STATE(59)] = 709,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote1, 3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3), SHIFT(58),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3), SHIFT(44),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3), SHIFT(43),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3), SHIFT(46),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3), SHIFT(48),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3), SHIFT(51),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(58),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(45),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(44),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(43),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(46),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(48),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(51),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote1, 2),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2), SHIFT(58),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2), SHIFT(44),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2), SHIFT(43),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2), SHIFT(46),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2), SHIFT(48),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2), SHIFT(51),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote2, 3),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3), SHIFT(58),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3), SHIFT(43),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3), SHIFT(46),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3), SHIFT(48),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3), SHIFT(51),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote2, 2),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2), SHIFT(58),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2), SHIFT(43),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2), SHIFT(46),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2), SHIFT(48),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2), SHIFT(51),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 1),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote3, 3),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3), SHIFT(58),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3), SHIFT(46),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3), SHIFT(48),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3), SHIFT(51),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(58),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(45),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(44),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(43),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(46),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(48),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(51),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote3, 2),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 2), SHIFT(58),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 2), SHIFT(46),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 2), SHIFT(48),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 2), SHIFT(51),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote4, 3),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 3), SHIFT(58),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 3), SHIFT(48),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 3), SHIFT(51),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote4, 2),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 2), SHIFT(58),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 2), SHIFT(48),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 2), SHIFT(51),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote1_repeat2, 2),
  [199] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat2, 2), SHIFT_REPEAT(58),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat2, 2), SHIFT_REPEAT(44),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat2, 2), SHIFT_REPEAT(43),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat2, 2), SHIFT_REPEAT(46),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat2, 2), SHIFT_REPEAT(48),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat2, 2), SHIFT_REPEAT(51),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote1, 4),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4), SHIFT(58),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4), SHIFT(44),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4), SHIFT(43),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4), SHIFT(46),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4), SHIFT(48),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4), SHIFT(51),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote5, 3),
  [239] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 3), SHIFT(58),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 3), SHIFT(51),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(58),
  [250] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(43),
  [253] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(46),
  [256] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(48),
  [259] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(51),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote5, 2),
  [264] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 2), SHIFT(58),
  [267] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 2), SHIFT(51),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote2, 4),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4), SHIFT(58),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4), SHIFT(43),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4), SHIFT(46),
  [281] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4), SHIFT(48),
  [284] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4), SHIFT(51),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2),
  [289] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2), SHIFT_REPEAT(58),
  [292] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2), SHIFT_REPEAT(46),
  [295] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2), SHIFT_REPEAT(48),
  [298] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2), SHIFT_REPEAT(51),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote3, 4),
  [303] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 4), SHIFT(58),
  [306] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 4), SHIFT(46),
  [309] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 4), SHIFT(48),
  [312] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 4), SHIFT(51),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote6, 2),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote4_repeat1, 2),
  [319] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote4_repeat1, 2), SHIFT_REPEAT(58),
  [322] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote4_repeat1, 2), SHIFT_REPEAT(48),
  [325] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote4_repeat1, 2), SHIFT_REPEAT(51),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote4, 4),
  [330] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 4), SHIFT(58),
  [333] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 4), SHIFT(48),
  [336] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 4), SHIFT(51),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote6, 3),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote5_repeat1, 2),
  [343] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote5_repeat1, 2), SHIFT_REPEAT(58),
  [346] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote5_repeat1, 2), SHIFT_REPEAT(51),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2),
  [351] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(34),
  [354] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(31),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote5, 4),
  [359] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 4), SHIFT(58),
  [362] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 4), SHIFT(51),
  [365] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 1, .production_id = 1),
  [367] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote1_repeat1, 1, .production_id = 1),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote6, 4),
  [371] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote6_repeat1, 2),
  [373] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_carryover_tag, 3),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [411] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_norg2(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
