#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 62
#define LARGE_STATE_COUNT 16
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 1
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 2

enum {
  sym_word = 1,
  sym_space = 2,
  sym_line_break = 3,
  anon_sym_PLUS = 4,
  anon_sym_GT = 5,
  anon_sym_GT_GT = 6,
  anon_sym_GT_GT_GT = 7,
  anon_sym_GT_GT_GT_GT = 8,
  anon_sym_GT_GT_GT_GT_GT = 9,
  anon_sym_GT_GT_GT_GT_GT_GT = 10,
  sym_document = 11,
  sym_paragraph = 12,
  sym_paragraph_segment = 13,
  sym__paragraph_element = 14,
  sym_carryover_tag = 15,
  sym_quote = 16,
  sym_quote1 = 17,
  sym_quote2 = 18,
  sym_quote3 = 19,
  sym_quote4 = 20,
  sym_quote5 = 21,
  sym_quote6 = 22,
  aux_sym_document_repeat1 = 23,
  aux_sym_paragraph_repeat1 = 24,
  aux_sym_paragraph_segment_repeat1 = 25,
  aux_sym_quote_repeat1 = 26,
  aux_sym_quote1_repeat1 = 27,
  aux_sym_quote2_repeat1 = 28,
  aux_sym_quote3_repeat1 = 29,
  aux_sym_quote4_repeat1 = 30,
  aux_sym_quote5_repeat1 = 31,
  aux_sym_quote6_repeat1 = 32,
  anon_alias_sym_tag_name = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_word] = "_word",
  [sym_space] = "_space",
  [sym_line_break] = "_line_break",
  [anon_sym_PLUS] = "+",
  [anon_sym_GT] = "> ",
  [anon_sym_GT_GT] = ">> ",
  [anon_sym_GT_GT_GT] = ">>> ",
  [anon_sym_GT_GT_GT_GT] = ">>>> ",
  [anon_sym_GT_GT_GT_GT_GT] = ">>>>> ",
  [anon_sym_GT_GT_GT_GT_GT_GT] = ">>>>>> ",
  [sym_document] = "document",
  [sym_paragraph] = "paragraph",
  [sym_paragraph_segment] = "paragraph_segment",
  [sym__paragraph_element] = "_paragraph_element",
  [sym_carryover_tag] = "carryover_tag",
  [sym_quote] = "quote",
  [sym_quote1] = "quote1",
  [sym_quote2] = "quote2",
  [sym_quote3] = "quote3",
  [sym_quote4] = "quote4",
  [sym_quote5] = "quote5",
  [sym_quote6] = "quote6",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_paragraph_segment_repeat1] = "paragraph_segment_repeat1",
  [aux_sym_quote_repeat1] = "quote_repeat1",
  [aux_sym_quote1_repeat1] = "quote1_repeat1",
  [aux_sym_quote2_repeat1] = "quote2_repeat1",
  [aux_sym_quote3_repeat1] = "quote3_repeat1",
  [aux_sym_quote4_repeat1] = "quote4_repeat1",
  [aux_sym_quote5_repeat1] = "quote5_repeat1",
  [aux_sym_quote6_repeat1] = "quote6_repeat1",
  [anon_alias_sym_tag_name] = "tag_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_word] = sym_word,
  [sym_space] = sym_space,
  [sym_line_break] = sym_line_break,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_GT_GT_GT] = anon_sym_GT_GT_GT,
  [anon_sym_GT_GT_GT_GT] = anon_sym_GT_GT_GT_GT,
  [anon_sym_GT_GT_GT_GT_GT] = anon_sym_GT_GT_GT_GT_GT,
  [anon_sym_GT_GT_GT_GT_GT_GT] = anon_sym_GT_GT_GT_GT_GT_GT,
  [sym_document] = sym_document,
  [sym_paragraph] = sym_paragraph,
  [sym_paragraph_segment] = sym_paragraph_segment,
  [sym__paragraph_element] = sym__paragraph_element,
  [sym_carryover_tag] = sym_carryover_tag,
  [sym_quote] = sym_quote,
  [sym_quote1] = sym_quote1,
  [sym_quote2] = sym_quote2,
  [sym_quote3] = sym_quote3,
  [sym_quote4] = sym_quote4,
  [sym_quote5] = sym_quote5,
  [sym_quote6] = sym_quote6,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_paragraph_segment_repeat1] = aux_sym_paragraph_segment_repeat1,
  [aux_sym_quote_repeat1] = aux_sym_quote_repeat1,
  [aux_sym_quote1_repeat1] = aux_sym_quote1_repeat1,
  [aux_sym_quote2_repeat1] = aux_sym_quote2_repeat1,
  [aux_sym_quote3_repeat1] = aux_sym_quote3_repeat1,
  [aux_sym_quote4_repeat1] = aux_sym_quote4_repeat1,
  [aux_sym_quote5_repeat1] = aux_sym_quote5_repeat1,
  [aux_sym_quote6_repeat1] = aux_sym_quote6_repeat1,
  [anon_alias_sym_tag_name] = anon_alias_sym_tag_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = false,
  },
  [sym_space] = {
    .visible = true,
    .named = false,
  },
  [sym_line_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_GT_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph_segment] = {
    .visible = true,
    .named = true,
  },
  [sym__paragraph_element] = {
    .visible = false,
    .named = true,
  },
  [sym_carryover_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_quote1] = {
    .visible = true,
    .named = true,
  },
  [sym_quote2] = {
    .visible = true,
    .named = true,
  },
  [sym_quote3] = {
    .visible = true,
    .named = true,
  },
  [sym_quote4] = {
    .visible = true,
    .named = true,
  },
  [sym_quote5] = {
    .visible = true,
    .named = true,
  },
  [sym_quote6] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_segment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote1_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote2_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote3_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote4_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote5_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote6_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_tag_name] = {
    .visible = true,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = anon_alias_sym_tag_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == 11) ADVANCE(12);
      if (lookahead == '\r') SKIP(8)
      if (lookahead == '+') ADVANCE(14);
      if (lookahead == '>') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(15);
      if (lookahead == '>') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(16);
      if (lookahead == '>') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '>') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == '>') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == '>') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == 11) ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_space);
      if (lookahead == 11) ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_space);
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == ' ') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_line_break);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT_GT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT_GT_GT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT_GT_GT_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 7},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_space] = ACTIONS(1),
    [sym_line_break] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_GT_GT_GT] = ACTIONS(1),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(1),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(1),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(60),
    [sym_paragraph] = STATE(2),
    [sym_paragraph_segment] = STATE(23),
    [sym__paragraph_element] = STATE(34),
    [sym_carryover_tag] = STATE(53),
    [sym_quote] = STATE(2),
    [sym_quote1] = STATE(5),
    [sym_quote2] = STATE(5),
    [sym_quote3] = STATE(5),
    [sym_quote4] = STATE(5),
    [sym_quote5] = STATE(5),
    [sym_quote6] = STATE(5),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(23),
    [aux_sym_paragraph_segment_repeat1] = STATE(34),
    [aux_sym_quote_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_word] = ACTIONS(5),
    [sym_space] = ACTIONS(5),
    [sym_line_break] = ACTIONS(7),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_GT_GT] = ACTIONS(13),
    [anon_sym_GT_GT_GT] = ACTIONS(15),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(17),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(19),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(21),
  },
  [2] = {
    [sym_paragraph] = STATE(3),
    [sym_paragraph_segment] = STATE(23),
    [sym__paragraph_element] = STATE(34),
    [sym_carryover_tag] = STATE(53),
    [sym_quote] = STATE(3),
    [sym_quote1] = STATE(5),
    [sym_quote2] = STATE(5),
    [sym_quote3] = STATE(5),
    [sym_quote4] = STATE(5),
    [sym_quote5] = STATE(5),
    [sym_quote6] = STATE(5),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(23),
    [aux_sym_paragraph_segment_repeat1] = STATE(34),
    [aux_sym_quote_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_word] = ACTIONS(5),
    [sym_space] = ACTIONS(5),
    [sym_line_break] = ACTIONS(7),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_GT_GT] = ACTIONS(13),
    [anon_sym_GT_GT_GT] = ACTIONS(15),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(17),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(19),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(21),
  },
  [3] = {
    [sym_paragraph] = STATE(3),
    [sym_paragraph_segment] = STATE(23),
    [sym__paragraph_element] = STATE(34),
    [sym_carryover_tag] = STATE(53),
    [sym_quote] = STATE(3),
    [sym_quote1] = STATE(5),
    [sym_quote2] = STATE(5),
    [sym_quote3] = STATE(5),
    [sym_quote4] = STATE(5),
    [sym_quote5] = STATE(5),
    [sym_quote6] = STATE(5),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(23),
    [aux_sym_paragraph_segment_repeat1] = STATE(34),
    [aux_sym_quote_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_word] = ACTIONS(27),
    [sym_space] = ACTIONS(27),
    [sym_line_break] = ACTIONS(30),
    [anon_sym_PLUS] = ACTIONS(33),
    [anon_sym_GT] = ACTIONS(36),
    [anon_sym_GT_GT] = ACTIONS(39),
    [anon_sym_GT_GT_GT] = ACTIONS(42),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(45),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(48),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(51),
  },
  [4] = {
    [sym_carryover_tag] = STATE(53),
    [sym_quote1] = STATE(4),
    [sym_quote2] = STATE(4),
    [sym_quote3] = STATE(4),
    [sym_quote4] = STATE(4),
    [sym_quote5] = STATE(4),
    [sym_quote6] = STATE(4),
    [aux_sym_quote_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(54),
    [sym_word] = ACTIONS(56),
    [sym_space] = ACTIONS(56),
    [sym_line_break] = ACTIONS(54),
    [anon_sym_PLUS] = ACTIONS(58),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_GT_GT] = ACTIONS(64),
    [anon_sym_GT_GT_GT] = ACTIONS(67),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(70),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(73),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(76),
  },
  [5] = {
    [sym_carryover_tag] = STATE(53),
    [sym_quote1] = STATE(4),
    [sym_quote2] = STATE(4),
    [sym_quote3] = STATE(4),
    [sym_quote4] = STATE(4),
    [sym_quote5] = STATE(4),
    [sym_quote6] = STATE(4),
    [aux_sym_quote_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(79),
    [sym_word] = ACTIONS(81),
    [sym_space] = ACTIONS(81),
    [sym_line_break] = ACTIONS(79),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_GT_GT] = ACTIONS(13),
    [anon_sym_GT_GT_GT] = ACTIONS(15),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(17),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(19),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(21),
  },
  [6] = {
    [sym_carryover_tag] = STATE(54),
    [sym_quote2] = STATE(7),
    [sym_quote3] = STATE(7),
    [sym_quote4] = STATE(7),
    [sym_quote5] = STATE(7),
    [sym_quote6] = STATE(7),
    [aux_sym_quote1_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(83),
    [sym_word] = ACTIONS(85),
    [sym_space] = ACTIONS(85),
    [sym_line_break] = ACTIONS(83),
    [anon_sym_PLUS] = ACTIONS(87),
    [anon_sym_GT] = ACTIONS(83),
    [anon_sym_GT_GT] = ACTIONS(90),
    [anon_sym_GT_GT_GT] = ACTIONS(93),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(96),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(99),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(102),
  },
  [7] = {
    [sym_carryover_tag] = STATE(54),
    [sym_quote2] = STATE(7),
    [sym_quote3] = STATE(7),
    [sym_quote4] = STATE(7),
    [sym_quote5] = STATE(7),
    [sym_quote6] = STATE(7),
    [aux_sym_quote1_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(105),
    [sym_word] = ACTIONS(107),
    [sym_space] = ACTIONS(107),
    [sym_line_break] = ACTIONS(105),
    [anon_sym_PLUS] = ACTIONS(109),
    [anon_sym_GT] = ACTIONS(105),
    [anon_sym_GT_GT] = ACTIONS(112),
    [anon_sym_GT_GT_GT] = ACTIONS(115),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(118),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(121),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(124),
  },
  [8] = {
    [sym_carryover_tag] = STATE(54),
    [sym_quote2] = STATE(6),
    [sym_quote3] = STATE(6),
    [sym_quote4] = STATE(6),
    [sym_quote5] = STATE(6),
    [sym_quote6] = STATE(6),
    [aux_sym_quote1_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(127),
    [sym_word] = ACTIONS(129),
    [sym_space] = ACTIONS(129),
    [sym_line_break] = ACTIONS(127),
    [anon_sym_PLUS] = ACTIONS(131),
    [anon_sym_GT] = ACTIONS(127),
    [anon_sym_GT_GT] = ACTIONS(134),
    [anon_sym_GT_GT_GT] = ACTIONS(137),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(140),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(143),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(146),
  },
  [9] = {
    [sym_carryover_tag] = STATE(54),
    [sym_quote2] = STATE(7),
    [sym_quote3] = STATE(7),
    [sym_quote4] = STATE(7),
    [sym_quote5] = STATE(7),
    [sym_quote6] = STATE(7),
    [aux_sym_quote1_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(127),
    [sym_word] = ACTIONS(129),
    [sym_space] = ACTIONS(129),
    [sym_line_break] = ACTIONS(127),
    [anon_sym_PLUS] = ACTIONS(131),
    [anon_sym_GT] = ACTIONS(127),
    [anon_sym_GT_GT] = ACTIONS(134),
    [anon_sym_GT_GT_GT] = ACTIONS(137),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(140),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(143),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(146),
  },
  [10] = {
    [sym_carryover_tag] = STATE(54),
    [sym_quote2] = STATE(9),
    [sym_quote3] = STATE(9),
    [sym_quote4] = STATE(9),
    [sym_quote5] = STATE(9),
    [sym_quote6] = STATE(9),
    [aux_sym_quote1_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(149),
    [sym_word] = ACTIONS(151),
    [sym_space] = ACTIONS(151),
    [sym_line_break] = ACTIONS(149),
    [anon_sym_PLUS] = ACTIONS(153),
    [anon_sym_GT] = ACTIONS(149),
    [anon_sym_GT_GT] = ACTIONS(156),
    [anon_sym_GT_GT_GT] = ACTIONS(159),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(162),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(165),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(168),
  },
  [11] = {
    [sym_carryover_tag] = STATE(55),
    [sym_quote3] = STATE(14),
    [sym_quote4] = STATE(14),
    [sym_quote5] = STATE(14),
    [sym_quote6] = STATE(14),
    [aux_sym_quote2_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(171),
    [sym_word] = ACTIONS(173),
    [sym_space] = ACTIONS(173),
    [sym_line_break] = ACTIONS(171),
    [anon_sym_PLUS] = ACTIONS(175),
    [anon_sym_GT] = ACTIONS(171),
    [anon_sym_GT_GT] = ACTIONS(171),
    [anon_sym_GT_GT_GT] = ACTIONS(178),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(181),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(184),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(187),
  },
  [12] = {
    [sym_carryover_tag] = STATE(55),
    [sym_quote3] = STATE(15),
    [sym_quote4] = STATE(15),
    [sym_quote5] = STATE(15),
    [sym_quote6] = STATE(15),
    [aux_sym_quote2_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(171),
    [sym_word] = ACTIONS(173),
    [sym_space] = ACTIONS(173),
    [sym_line_break] = ACTIONS(171),
    [anon_sym_PLUS] = ACTIONS(175),
    [anon_sym_GT] = ACTIONS(171),
    [anon_sym_GT_GT] = ACTIONS(171),
    [anon_sym_GT_GT_GT] = ACTIONS(178),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(181),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(184),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(187),
  },
  [13] = {
    [sym_carryover_tag] = STATE(55),
    [sym_quote3] = STATE(12),
    [sym_quote4] = STATE(12),
    [sym_quote5] = STATE(12),
    [sym_quote6] = STATE(12),
    [aux_sym_quote2_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(190),
    [sym_word] = ACTIONS(192),
    [sym_space] = ACTIONS(192),
    [sym_line_break] = ACTIONS(190),
    [anon_sym_PLUS] = ACTIONS(194),
    [anon_sym_GT] = ACTIONS(190),
    [anon_sym_GT_GT] = ACTIONS(190),
    [anon_sym_GT_GT_GT] = ACTIONS(197),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(200),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(203),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(206),
  },
  [14] = {
    [sym_carryover_tag] = STATE(55),
    [sym_quote3] = STATE(15),
    [sym_quote4] = STATE(15),
    [sym_quote5] = STATE(15),
    [sym_quote6] = STATE(15),
    [aux_sym_quote2_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(209),
    [sym_word] = ACTIONS(211),
    [sym_space] = ACTIONS(211),
    [sym_line_break] = ACTIONS(209),
    [anon_sym_PLUS] = ACTIONS(213),
    [anon_sym_GT] = ACTIONS(209),
    [anon_sym_GT_GT] = ACTIONS(209),
    [anon_sym_GT_GT_GT] = ACTIONS(216),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(219),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(222),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(225),
  },
  [15] = {
    [sym_carryover_tag] = STATE(55),
    [sym_quote3] = STATE(15),
    [sym_quote4] = STATE(15),
    [sym_quote5] = STATE(15),
    [sym_quote6] = STATE(15),
    [aux_sym_quote2_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(228),
    [sym_word] = ACTIONS(230),
    [sym_space] = ACTIONS(230),
    [sym_line_break] = ACTIONS(228),
    [anon_sym_PLUS] = ACTIONS(232),
    [anon_sym_GT] = ACTIONS(228),
    [anon_sym_GT_GT] = ACTIONS(228),
    [anon_sym_GT_GT_GT] = ACTIONS(235),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(238),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(241),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(244),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(251), 1,
      anon_sym_PLUS,
    ACTIONS(254), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(257), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(260), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(56), 1,
      sym_carryover_tag,
    ACTIONS(249), 2,
      sym_word,
      sym_space,
    STATE(20), 4,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote3_repeat1,
    ACTIONS(247), 5,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
  [33] = 8,
    ACTIONS(267), 1,
      anon_sym_PLUS,
    ACTIONS(270), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(273), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(276), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(56), 1,
      sym_carryover_tag,
    ACTIONS(265), 2,
      sym_word,
      sym_space,
    STATE(16), 4,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote3_repeat1,
    ACTIONS(263), 5,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
  [66] = 8,
    ACTIONS(251), 1,
      anon_sym_PLUS,
    ACTIONS(254), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(257), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(260), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(56), 1,
      sym_carryover_tag,
    ACTIONS(249), 2,
      sym_word,
      sym_space,
    STATE(19), 4,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote3_repeat1,
    ACTIONS(247), 5,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
  [99] = 8,
    ACTIONS(283), 1,
      anon_sym_PLUS,
    ACTIONS(286), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(289), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(292), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(56), 1,
      sym_carryover_tag,
    ACTIONS(281), 2,
      sym_word,
      sym_space,
    STATE(20), 4,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote3_repeat1,
    ACTIONS(279), 5,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
  [132] = 8,
    ACTIONS(299), 1,
      anon_sym_PLUS,
    ACTIONS(302), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(305), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(308), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(56), 1,
      sym_carryover_tag,
    ACTIONS(297), 2,
      sym_word,
      sym_space,
    STATE(20), 4,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote3_repeat1,
    ACTIONS(295), 5,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
  [165] = 5,
    ACTIONS(316), 1,
      sym_line_break,
    ACTIONS(313), 2,
      sym_word,
      sym_space,
    STATE(21), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(311), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [191] = 7,
    ACTIONS(323), 1,
      anon_sym_PLUS,
    ACTIONS(326), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(329), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(57), 1,
      sym_carryover_tag,
    ACTIONS(321), 2,
      sym_word,
      sym_space,
    STATE(27), 3,
      sym_quote5,
      sym_quote6,
      aux_sym_quote4_repeat1,
    ACTIONS(319), 6,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
  [221] = 5,
    ACTIONS(337), 1,
      sym_line_break,
    ACTIONS(334), 2,
      sym_word,
      sym_space,
    STATE(21), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(332), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [247] = 7,
    ACTIONS(344), 1,
      anon_sym_PLUS,
    ACTIONS(347), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(350), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(57), 1,
      sym_carryover_tag,
    ACTIONS(342), 2,
      sym_word,
      sym_space,
    STATE(27), 3,
      sym_quote5,
      sym_quote6,
      aux_sym_quote4_repeat1,
    ACTIONS(340), 6,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
  [277] = 7,
    ACTIONS(357), 1,
      anon_sym_PLUS,
    ACTIONS(360), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(363), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(57), 1,
      sym_carryover_tag,
    ACTIONS(355), 2,
      sym_word,
      sym_space,
    STATE(22), 3,
      sym_quote5,
      sym_quote6,
      aux_sym_quote4_repeat1,
    ACTIONS(353), 6,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
  [307] = 7,
    ACTIONS(323), 1,
      anon_sym_PLUS,
    ACTIONS(326), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(329), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(57), 1,
      sym_carryover_tag,
    ACTIONS(321), 2,
      sym_word,
      sym_space,
    STATE(24), 3,
      sym_quote5,
      sym_quote6,
      aux_sym_quote4_repeat1,
    ACTIONS(319), 6,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
  [337] = 7,
    ACTIONS(370), 1,
      anon_sym_PLUS,
    ACTIONS(373), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(376), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(57), 1,
      sym_carryover_tag,
    ACTIONS(368), 2,
      sym_word,
      sym_space,
    STATE(27), 3,
      sym_quote5,
      sym_quote6,
      aux_sym_quote4_repeat1,
    ACTIONS(366), 6,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
  [367] = 6,
    ACTIONS(383), 1,
      anon_sym_PLUS,
    ACTIONS(386), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(58), 1,
      sym_carryover_tag,
    ACTIONS(381), 2,
      sym_word,
      sym_space,
    STATE(28), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(379), 7,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
  [394] = 6,
    ACTIONS(393), 1,
      anon_sym_PLUS,
    ACTIONS(396), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(58), 1,
      sym_carryover_tag,
    ACTIONS(391), 2,
      sym_word,
      sym_space,
    STATE(31), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(389), 7,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
  [421] = 6,
    ACTIONS(403), 1,
      anon_sym_PLUS,
    ACTIONS(406), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(58), 1,
      sym_carryover_tag,
    ACTIONS(401), 2,
      sym_word,
      sym_space,
    STATE(32), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(399), 7,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
  [448] = 6,
    ACTIONS(413), 1,
      anon_sym_PLUS,
    ACTIONS(416), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(58), 1,
      sym_carryover_tag,
    ACTIONS(411), 2,
      sym_word,
      sym_space,
    STATE(28), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(409), 7,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
  [475] = 6,
    ACTIONS(393), 1,
      anon_sym_PLUS,
    ACTIONS(396), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(58), 1,
      sym_carryover_tag,
    ACTIONS(391), 2,
      sym_word,
      sym_space,
    STATE(28), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(389), 7,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
  [502] = 3,
    ACTIONS(421), 2,
      sym_word,
      sym_space,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(419), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [522] = 3,
    ACTIONS(426), 2,
      sym_word,
      sym_space,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(424), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [542] = 3,
    STATE(38), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(430), 2,
      sym_word,
      sym_space,
    ACTIONS(428), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [561] = 3,
    STATE(38), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(434), 2,
      sym_word,
      sym_space,
    ACTIONS(432), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [580] = 3,
    STATE(36), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(430), 2,
      sym_word,
      sym_space,
    ACTIONS(428), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [599] = 3,
    STATE(38), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(438), 2,
      sym_word,
      sym_space,
    ACTIONS(436), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [618] = 3,
    STATE(35), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(442), 2,
      sym_word,
      sym_space,
    ACTIONS(440), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [637] = 5,
    ACTIONS(7), 1,
      sym_line_break,
    STATE(11), 1,
      sym_paragraph,
    ACTIONS(5), 2,
      sym_word,
      sym_space,
    STATE(23), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
  [656] = 5,
    ACTIONS(7), 1,
      sym_line_break,
    STATE(29), 1,
      sym_paragraph,
    ACTIONS(5), 2,
      sym_word,
      sym_space,
    STATE(23), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
  [675] = 5,
    ACTIONS(7), 1,
      sym_line_break,
    STATE(8), 1,
      sym_paragraph,
    ACTIONS(5), 2,
      sym_word,
      sym_space,
    STATE(23), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
  [694] = 5,
    ACTIONS(7), 1,
      sym_line_break,
    STATE(39), 1,
      sym_paragraph,
    ACTIONS(5), 2,
      sym_word,
      sym_space,
    STATE(23), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
  [713] = 5,
    ACTIONS(7), 1,
      sym_line_break,
    STATE(25), 1,
      sym_paragraph,
    ACTIONS(5), 2,
      sym_word,
      sym_space,
    STATE(23), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
  [732] = 5,
    ACTIONS(7), 1,
      sym_line_break,
    STATE(17), 1,
      sym_paragraph,
    ACTIONS(5), 2,
      sym_word,
      sym_space,
    STATE(23), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
  [751] = 5,
    ACTIONS(7), 1,
      sym_line_break,
    STATE(18), 1,
      sym_paragraph,
    ACTIONS(5), 2,
      sym_word,
      sym_space,
    STATE(23), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
  [770] = 5,
    ACTIONS(7), 1,
      sym_line_break,
    STATE(10), 1,
      sym_paragraph,
    ACTIONS(5), 2,
      sym_word,
      sym_space,
    STATE(23), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
  [789] = 5,
    ACTIONS(7), 1,
      sym_line_break,
    STATE(30), 1,
      sym_paragraph,
    ACTIONS(5), 2,
      sym_word,
      sym_space,
    STATE(23), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
  [808] = 5,
    ACTIONS(7), 1,
      sym_line_break,
    STATE(26), 1,
      sym_paragraph,
    ACTIONS(5), 2,
      sym_word,
      sym_space,
    STATE(23), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
  [827] = 5,
    ACTIONS(7), 1,
      sym_line_break,
    STATE(13), 1,
      sym_paragraph,
    ACTIONS(5), 2,
      sym_word,
      sym_space,
    STATE(23), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
  [846] = 5,
    ACTIONS(7), 1,
      sym_line_break,
    STATE(37), 1,
      sym_paragraph,
    ACTIONS(5), 2,
      sym_word,
      sym_space,
    STATE(23), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
  [865] = 1,
    ACTIONS(444), 6,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [874] = 6,
    ACTIONS(446), 1,
      anon_sym_GT,
    ACTIONS(448), 1,
      anon_sym_GT_GT,
    ACTIONS(450), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(452), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(454), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(456), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [893] = 5,
    ACTIONS(448), 1,
      anon_sym_GT_GT,
    ACTIONS(450), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(452), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(454), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(456), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [909] = 4,
    ACTIONS(450), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(452), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(454), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(456), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [922] = 3,
    ACTIONS(452), 1,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(454), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(456), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [932] = 2,
    ACTIONS(454), 1,
      anon_sym_GT_GT_GT_GT_GT,
    ACTIONS(456), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [939] = 1,
    ACTIONS(456), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [943] = 1,
    ACTIONS(458), 1,
      sym_word,
  [947] = 1,
    ACTIONS(460), 1,
      ts_builtin_sym_end,
  [951] = 1,
    ACTIONS(462), 1,
      sym_line_break,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(16)] = 0,
  [SMALL_STATE(17)] = 33,
  [SMALL_STATE(18)] = 66,
  [SMALL_STATE(19)] = 99,
  [SMALL_STATE(20)] = 132,
  [SMALL_STATE(21)] = 165,
  [SMALL_STATE(22)] = 191,
  [SMALL_STATE(23)] = 221,
  [SMALL_STATE(24)] = 247,
  [SMALL_STATE(25)] = 277,
  [SMALL_STATE(26)] = 307,
  [SMALL_STATE(27)] = 337,
  [SMALL_STATE(28)] = 367,
  [SMALL_STATE(29)] = 394,
  [SMALL_STATE(30)] = 421,
  [SMALL_STATE(31)] = 448,
  [SMALL_STATE(32)] = 475,
  [SMALL_STATE(33)] = 502,
  [SMALL_STATE(34)] = 522,
  [SMALL_STATE(35)] = 542,
  [SMALL_STATE(36)] = 561,
  [SMALL_STATE(37)] = 580,
  [SMALL_STATE(38)] = 599,
  [SMALL_STATE(39)] = 618,
  [SMALL_STATE(40)] = 637,
  [SMALL_STATE(41)] = 656,
  [SMALL_STATE(42)] = 675,
  [SMALL_STATE(43)] = 694,
  [SMALL_STATE(44)] = 713,
  [SMALL_STATE(45)] = 732,
  [SMALL_STATE(46)] = 751,
  [SMALL_STATE(47)] = 770,
  [SMALL_STATE(48)] = 789,
  [SMALL_STATE(49)] = 808,
  [SMALL_STATE(50)] = 827,
  [SMALL_STATE(51)] = 846,
  [SMALL_STATE(52)] = 865,
  [SMALL_STATE(53)] = 874,
  [SMALL_STATE(54)] = 893,
  [SMALL_STATE(55)] = 909,
  [SMALL_STATE(56)] = 922,
  [SMALL_STATE(57)] = 932,
  [SMALL_STATE(58)] = 939,
  [SMALL_STATE(59)] = 943,
  [SMALL_STATE(60)] = 947,
  [SMALL_STATE(61)] = 951,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(34),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(23),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(59),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(47),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(50),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(45),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(44),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(48),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(43),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote_repeat1, 2),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(59),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(47),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(50),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(45),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(44),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(48),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(43),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 1),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote1, 4),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote1, 4),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4), SHIFT(59),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4), SHIFT(50),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4), SHIFT(45),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4), SHIFT(44),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4), SHIFT(48),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4), SHIFT(43),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote1_repeat1, 2),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(59),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(50),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(45),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(44),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(48),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(43),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote1, 3),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote1, 3),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3), SHIFT(59),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3), SHIFT(50),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3), SHIFT(45),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3), SHIFT(44),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3), SHIFT(48),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3), SHIFT(43),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote1, 2),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote1, 2),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2), SHIFT(59),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2), SHIFT(50),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2), SHIFT(45),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2), SHIFT(44),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2), SHIFT(48),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2), SHIFT(43),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote2, 3),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote2, 3),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3), SHIFT(59),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3), SHIFT(45),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3), SHIFT(44),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3), SHIFT(48),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3), SHIFT(43),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote2, 2),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote2, 2),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2), SHIFT(59),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2), SHIFT(45),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2), SHIFT(44),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2), SHIFT(48),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2), SHIFT(43),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote2, 4),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote2, 4),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4), SHIFT(59),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4), SHIFT(45),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4), SHIFT(44),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4), SHIFT(48),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4), SHIFT(43),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote2_repeat1, 2),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(59),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(45),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(44),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(48),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(43),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote3, 3),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote3, 3),
  [251] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3), SHIFT(59),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3), SHIFT(44),
  [257] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3), SHIFT(48),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3), SHIFT(43),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote3, 2),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote3, 2),
  [267] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 2), SHIFT(59),
  [270] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 2), SHIFT(44),
  [273] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 2), SHIFT(48),
  [276] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 2), SHIFT(43),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote3, 4),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote3, 4),
  [283] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 4), SHIFT(59),
  [286] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 4), SHIFT(44),
  [289] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 4), SHIFT(48),
  [292] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 4), SHIFT(43),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote3_repeat1, 2),
  [299] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2), SHIFT_REPEAT(59),
  [302] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2), SHIFT_REPEAT(44),
  [305] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2), SHIFT_REPEAT(48),
  [308] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2), SHIFT_REPEAT(43),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [313] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(34),
  [316] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(21),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote4, 3),
  [321] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote4, 3),
  [323] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 3), SHIFT(59),
  [326] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 3), SHIFT(48),
  [329] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 3), SHIFT(43),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [334] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_paragraph, 1), SHIFT(34),
  [337] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_paragraph, 1), SHIFT(21),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote4, 4),
  [342] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote4, 4),
  [344] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 4), SHIFT(59),
  [347] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 4), SHIFT(48),
  [350] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 4), SHIFT(43),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote4, 2),
  [355] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote4, 2),
  [357] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 2), SHIFT(59),
  [360] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 2), SHIFT(48),
  [363] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 2), SHIFT(43),
  [366] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote4_repeat1, 2),
  [368] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote4_repeat1, 2),
  [370] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote4_repeat1, 2), SHIFT_REPEAT(59),
  [373] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote4_repeat1, 2), SHIFT_REPEAT(48),
  [376] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote4_repeat1, 2), SHIFT_REPEAT(43),
  [379] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote5_repeat1, 2),
  [381] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote5_repeat1, 2),
  [383] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote5_repeat1, 2), SHIFT_REPEAT(59),
  [386] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote5_repeat1, 2), SHIFT_REPEAT(43),
  [389] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote5, 3),
  [391] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote5, 3),
  [393] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 3), SHIFT(59),
  [396] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 3), SHIFT(43),
  [399] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote5, 2),
  [401] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote5, 2),
  [403] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 2), SHIFT(59),
  [406] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 2), SHIFT(43),
  [409] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote5, 4),
  [411] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote5, 4),
  [413] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 4), SHIFT(59),
  [416] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 4), SHIFT(43),
  [419] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_segment_repeat1, 2),
  [421] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_segment_repeat1, 2), SHIFT_REPEAT(33),
  [424] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph_segment, 1),
  [426] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [428] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote6, 3),
  [430] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote6, 3),
  [432] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote6, 4),
  [434] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote6, 4),
  [436] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote6_repeat1, 2),
  [438] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote6_repeat1, 2),
  [440] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote6, 2),
  [442] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote6, 2),
  [444] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_carryover_tag, 3, .production_id = 1),
  [446] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [448] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [450] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [452] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [454] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [456] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [458] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [460] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [462] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_norg2(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
