#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 1
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 4

enum {
  sym_word = 1,
  sym_space = 2,
  sym_punctuation = 3,
  sym_line_break = 4,
  anon_sym_PLUS = 5,
  sym_quote1_prefix = 6,
  sym_quote2_prefix = 7,
  sym_quote3_prefix = 8,
  sym_quote4_prefix = 9,
  sym_quote5_prefix = 10,
  anon_sym_GT_GT_GT_GT_GT_GT = 11,
  anon_sym_GT = 12,
  anon_sym_ = 13,
  sym_document = 14,
  sym_paragraph_break = 15,
  sym_paragraph = 16,
  sym_paragraph_segment = 17,
  sym__paragraph_element = 18,
  sym_carryover_tag = 19,
  sym_quote = 20,
  sym_quote6_prefix = 21,
  sym_quote1 = 22,
  sym_quote2 = 23,
  sym_quote3 = 24,
  sym_quote4 = 25,
  sym_quote5 = 26,
  sym_quote6 = 27,
  aux_sym_document_repeat1 = 28,
  aux_sym_paragraph_repeat1 = 29,
  aux_sym_paragraph_segment_repeat1 = 30,
  aux_sym_quote_repeat1 = 31,
  aux_sym_quote6_prefix_repeat1 = 32,
  aux_sym_quote1_repeat1 = 33,
  aux_sym_quote2_repeat1 = 34,
  aux_sym_quote3_repeat1 = 35,
  aux_sym_quote4_repeat1 = 36,
  aux_sym_quote5_repeat1 = 37,
  aux_sym_quote6_repeat1 = 38,
  anon_alias_sym_tag_name = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_word] = "_word",
  [sym_space] = "_space",
  [sym_punctuation] = "_punctuation",
  [sym_line_break] = "_line_break",
  [anon_sym_PLUS] = "+",
  [sym_quote1_prefix] = "quote1_prefix",
  [sym_quote2_prefix] = "quote2_prefix",
  [sym_quote3_prefix] = "quote3_prefix",
  [sym_quote4_prefix] = "quote4_prefix",
  [sym_quote5_prefix] = "quote5_prefix",
  [anon_sym_GT_GT_GT_GT_GT_GT] = ">>>>>>",
  [anon_sym_GT] = ">",
  [anon_sym_] = " ",
  [sym_document] = "document",
  [sym_paragraph_break] = "_paragraph_break",
  [sym_paragraph] = "paragraph",
  [sym_paragraph_segment] = "paragraph_segment",
  [sym__paragraph_element] = "_paragraph_element",
  [sym_carryover_tag] = "carryover_tag",
  [sym_quote] = "quote",
  [sym_quote6_prefix] = "quote6_prefix",
  [sym_quote1] = "quote1",
  [sym_quote2] = "quote2",
  [sym_quote3] = "quote3",
  [sym_quote4] = "quote4",
  [sym_quote5] = "quote5",
  [sym_quote6] = "quote6",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_paragraph_segment_repeat1] = "paragraph_segment_repeat1",
  [aux_sym_quote_repeat1] = "quote_repeat1",
  [aux_sym_quote6_prefix_repeat1] = "quote6_prefix_repeat1",
  [aux_sym_quote1_repeat1] = "quote1_repeat1",
  [aux_sym_quote2_repeat1] = "quote2_repeat1",
  [aux_sym_quote3_repeat1] = "quote3_repeat1",
  [aux_sym_quote4_repeat1] = "quote4_repeat1",
  [aux_sym_quote5_repeat1] = "quote5_repeat1",
  [aux_sym_quote6_repeat1] = "quote6_repeat1",
  [anon_alias_sym_tag_name] = "tag_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_word] = sym_word,
  [sym_space] = sym_space,
  [sym_punctuation] = sym_punctuation,
  [sym_line_break] = sym_line_break,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_quote1_prefix] = sym_quote1_prefix,
  [sym_quote2_prefix] = sym_quote2_prefix,
  [sym_quote3_prefix] = sym_quote3_prefix,
  [sym_quote4_prefix] = sym_quote4_prefix,
  [sym_quote5_prefix] = sym_quote5_prefix,
  [anon_sym_GT_GT_GT_GT_GT_GT] = anon_sym_GT_GT_GT_GT_GT_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_] = anon_sym_,
  [sym_document] = sym_document,
  [sym_paragraph_break] = sym_paragraph_break,
  [sym_paragraph] = sym_paragraph,
  [sym_paragraph_segment] = sym_paragraph_segment,
  [sym__paragraph_element] = sym__paragraph_element,
  [sym_carryover_tag] = sym_carryover_tag,
  [sym_quote] = sym_quote,
  [sym_quote6_prefix] = sym_quote6_prefix,
  [sym_quote1] = sym_quote1,
  [sym_quote2] = sym_quote2,
  [sym_quote3] = sym_quote3,
  [sym_quote4] = sym_quote4,
  [sym_quote5] = sym_quote5,
  [sym_quote6] = sym_quote6,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_paragraph_segment_repeat1] = aux_sym_paragraph_segment_repeat1,
  [aux_sym_quote_repeat1] = aux_sym_quote_repeat1,
  [aux_sym_quote6_prefix_repeat1] = aux_sym_quote6_prefix_repeat1,
  [aux_sym_quote1_repeat1] = aux_sym_quote1_repeat1,
  [aux_sym_quote2_repeat1] = aux_sym_quote2_repeat1,
  [aux_sym_quote3_repeat1] = aux_sym_quote3_repeat1,
  [aux_sym_quote4_repeat1] = aux_sym_quote4_repeat1,
  [aux_sym_quote5_repeat1] = aux_sym_quote5_repeat1,
  [aux_sym_quote6_repeat1] = aux_sym_quote6_repeat1,
  [anon_alias_sym_tag_name] = anon_alias_sym_tag_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = false,
  },
  [sym_space] = {
    .visible = true,
    .named = false,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = false,
  },
  [sym_line_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_quote1_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_quote2_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_quote3_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_quote4_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_quote5_prefix] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT_GT_GT_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph_break] = {
    .visible = true,
    .named = false,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph_segment] = {
    .visible = true,
    .named = true,
  },
  [sym__paragraph_element] = {
    .visible = false,
    .named = true,
  },
  [sym_carryover_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_quote6_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_quote1] = {
    .visible = true,
    .named = true,
  },
  [sym_quote2] = {
    .visible = true,
    .named = true,
  },
  [sym_quote3] = {
    .visible = true,
    .named = true,
  },
  [sym_quote4] = {
    .visible = true,
    .named = true,
  },
  [sym_quote5] = {
    .visible = true,
    .named = true,
  },
  [sym_quote6] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_segment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote6_prefix_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote1_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote2_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote3_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote4_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote5_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote6_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_tag_name] = {
    .visible = true,
    .named = false,
  },
};

enum {
  field_content = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
  [1] =
    {field_content, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [1] = anon_alias_sym_tag_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == 11) ADVANCE(12);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == '>') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(14);
      if (lookahead == ',' ||
          lookahead == '.') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(16);
      if (lookahead == '>') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '>') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == '>') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == '>') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(20);
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '>') ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == 11) ADVANCE(12);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == '>') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(14);
      if (lookahead == ',' ||
          lookahead == '.') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_space);
      if (lookahead == 11) ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_space);
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == ' ') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_line_break);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_quote1_prefix);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_quote2_prefix);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_quote3_prefix);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_quote4_prefix);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_quote5_prefix);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT_GT_GT_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 8},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 8},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 8},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 8},
  [65] = {.lex_state = 8},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_space] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_line_break] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(66),
    [sym_paragraph_break] = STATE(2),
    [sym_paragraph] = STATE(2),
    [sym_paragraph_segment] = STATE(29),
    [sym__paragraph_element] = STATE(33),
    [sym_carryover_tag] = STATE(54),
    [sym_quote] = STATE(2),
    [sym_quote6_prefix] = STATE(52),
    [sym_quote1] = STATE(5),
    [sym_quote2] = STATE(5),
    [sym_quote3] = STATE(5),
    [sym_quote4] = STATE(5),
    [sym_quote5] = STATE(5),
    [sym_quote6] = STATE(5),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(29),
    [aux_sym_paragraph_segment_repeat1] = STATE(33),
    [aux_sym_quote_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_word] = ACTIONS(5),
    [sym_space] = ACTIONS(5),
    [sym_punctuation] = ACTIONS(5),
    [sym_line_break] = ACTIONS(7),
    [anon_sym_PLUS] = ACTIONS(9),
    [sym_quote1_prefix] = ACTIONS(11),
    [sym_quote2_prefix] = ACTIONS(13),
    [sym_quote3_prefix] = ACTIONS(15),
    [sym_quote4_prefix] = ACTIONS(17),
    [sym_quote5_prefix] = ACTIONS(19),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(21),
  },
  [2] = {
    [sym_paragraph_break] = STATE(3),
    [sym_paragraph] = STATE(3),
    [sym_paragraph_segment] = STATE(29),
    [sym__paragraph_element] = STATE(33),
    [sym_carryover_tag] = STATE(54),
    [sym_quote] = STATE(3),
    [sym_quote6_prefix] = STATE(52),
    [sym_quote1] = STATE(5),
    [sym_quote2] = STATE(5),
    [sym_quote3] = STATE(5),
    [sym_quote4] = STATE(5),
    [sym_quote5] = STATE(5),
    [sym_quote6] = STATE(5),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(29),
    [aux_sym_paragraph_segment_repeat1] = STATE(33),
    [aux_sym_quote_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_word] = ACTIONS(5),
    [sym_space] = ACTIONS(5),
    [sym_punctuation] = ACTIONS(5),
    [sym_line_break] = ACTIONS(7),
    [anon_sym_PLUS] = ACTIONS(9),
    [sym_quote1_prefix] = ACTIONS(11),
    [sym_quote2_prefix] = ACTIONS(13),
    [sym_quote3_prefix] = ACTIONS(15),
    [sym_quote4_prefix] = ACTIONS(17),
    [sym_quote5_prefix] = ACTIONS(19),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(21),
  },
  [3] = {
    [sym_paragraph_break] = STATE(3),
    [sym_paragraph] = STATE(3),
    [sym_paragraph_segment] = STATE(29),
    [sym__paragraph_element] = STATE(33),
    [sym_carryover_tag] = STATE(54),
    [sym_quote] = STATE(3),
    [sym_quote6_prefix] = STATE(52),
    [sym_quote1] = STATE(5),
    [sym_quote2] = STATE(5),
    [sym_quote3] = STATE(5),
    [sym_quote4] = STATE(5),
    [sym_quote5] = STATE(5),
    [sym_quote6] = STATE(5),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(29),
    [aux_sym_paragraph_segment_repeat1] = STATE(33),
    [aux_sym_quote_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_word] = ACTIONS(27),
    [sym_space] = ACTIONS(27),
    [sym_punctuation] = ACTIONS(27),
    [sym_line_break] = ACTIONS(30),
    [anon_sym_PLUS] = ACTIONS(33),
    [sym_quote1_prefix] = ACTIONS(36),
    [sym_quote2_prefix] = ACTIONS(39),
    [sym_quote3_prefix] = ACTIONS(42),
    [sym_quote4_prefix] = ACTIONS(45),
    [sym_quote5_prefix] = ACTIONS(48),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(51),
  },
  [4] = {
    [sym_carryover_tag] = STATE(54),
    [sym_quote6_prefix] = STATE(52),
    [sym_quote1] = STATE(4),
    [sym_quote2] = STATE(4),
    [sym_quote3] = STATE(4),
    [sym_quote4] = STATE(4),
    [sym_quote5] = STATE(4),
    [sym_quote6] = STATE(4),
    [aux_sym_quote_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(54),
    [sym_word] = ACTIONS(56),
    [sym_space] = ACTIONS(56),
    [sym_punctuation] = ACTIONS(56),
    [sym_line_break] = ACTIONS(54),
    [anon_sym_PLUS] = ACTIONS(58),
    [sym_quote1_prefix] = ACTIONS(61),
    [sym_quote2_prefix] = ACTIONS(64),
    [sym_quote3_prefix] = ACTIONS(67),
    [sym_quote4_prefix] = ACTIONS(70),
    [sym_quote5_prefix] = ACTIONS(73),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(76),
  },
  [5] = {
    [sym_carryover_tag] = STATE(54),
    [sym_quote6_prefix] = STATE(52),
    [sym_quote1] = STATE(4),
    [sym_quote2] = STATE(4),
    [sym_quote3] = STATE(4),
    [sym_quote4] = STATE(4),
    [sym_quote5] = STATE(4),
    [sym_quote6] = STATE(4),
    [aux_sym_quote_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(79),
    [sym_word] = ACTIONS(81),
    [sym_space] = ACTIONS(81),
    [sym_punctuation] = ACTIONS(81),
    [sym_line_break] = ACTIONS(79),
    [anon_sym_PLUS] = ACTIONS(9),
    [sym_quote1_prefix] = ACTIONS(11),
    [sym_quote2_prefix] = ACTIONS(13),
    [sym_quote3_prefix] = ACTIONS(15),
    [sym_quote4_prefix] = ACTIONS(17),
    [sym_quote5_prefix] = ACTIONS(19),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(21),
  },
  [6] = {
    [sym_carryover_tag] = STATE(56),
    [sym_quote6_prefix] = STATE(52),
    [sym_quote2] = STATE(9),
    [sym_quote3] = STATE(9),
    [sym_quote4] = STATE(9),
    [sym_quote5] = STATE(9),
    [sym_quote6] = STATE(9),
    [aux_sym_quote1_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(83),
    [sym_word] = ACTIONS(85),
    [sym_space] = ACTIONS(85),
    [sym_punctuation] = ACTIONS(85),
    [sym_line_break] = ACTIONS(83),
    [anon_sym_PLUS] = ACTIONS(87),
    [sym_quote1_prefix] = ACTIONS(83),
    [sym_quote2_prefix] = ACTIONS(90),
    [sym_quote3_prefix] = ACTIONS(93),
    [sym_quote4_prefix] = ACTIONS(96),
    [sym_quote5_prefix] = ACTIONS(99),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(102),
  },
  [7] = {
    [sym_carryover_tag] = STATE(56),
    [sym_quote6_prefix] = STATE(52),
    [sym_quote2] = STATE(9),
    [sym_quote3] = STATE(9),
    [sym_quote4] = STATE(9),
    [sym_quote5] = STATE(9),
    [sym_quote6] = STATE(9),
    [aux_sym_quote1_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(105),
    [sym_word] = ACTIONS(107),
    [sym_space] = ACTIONS(107),
    [sym_punctuation] = ACTIONS(107),
    [sym_line_break] = ACTIONS(105),
    [anon_sym_PLUS] = ACTIONS(109),
    [sym_quote1_prefix] = ACTIONS(105),
    [sym_quote2_prefix] = ACTIONS(112),
    [sym_quote3_prefix] = ACTIONS(115),
    [sym_quote4_prefix] = ACTIONS(118),
    [sym_quote5_prefix] = ACTIONS(121),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(124),
  },
  [8] = {
    [sym_carryover_tag] = STATE(56),
    [sym_quote6_prefix] = STATE(52),
    [sym_quote2] = STATE(6),
    [sym_quote3] = STATE(6),
    [sym_quote4] = STATE(6),
    [sym_quote5] = STATE(6),
    [sym_quote6] = STATE(6),
    [aux_sym_quote1_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(127),
    [sym_word] = ACTIONS(129),
    [sym_space] = ACTIONS(129),
    [sym_punctuation] = ACTIONS(129),
    [sym_line_break] = ACTIONS(127),
    [anon_sym_PLUS] = ACTIONS(131),
    [sym_quote1_prefix] = ACTIONS(127),
    [sym_quote2_prefix] = ACTIONS(134),
    [sym_quote3_prefix] = ACTIONS(137),
    [sym_quote4_prefix] = ACTIONS(140),
    [sym_quote5_prefix] = ACTIONS(143),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(146),
  },
  [9] = {
    [sym_carryover_tag] = STATE(56),
    [sym_quote6_prefix] = STATE(52),
    [sym_quote2] = STATE(9),
    [sym_quote3] = STATE(9),
    [sym_quote4] = STATE(9),
    [sym_quote5] = STATE(9),
    [sym_quote6] = STATE(9),
    [aux_sym_quote1_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(149),
    [sym_word] = ACTIONS(151),
    [sym_space] = ACTIONS(151),
    [sym_punctuation] = ACTIONS(151),
    [sym_line_break] = ACTIONS(149),
    [anon_sym_PLUS] = ACTIONS(153),
    [sym_quote1_prefix] = ACTIONS(149),
    [sym_quote2_prefix] = ACTIONS(156),
    [sym_quote3_prefix] = ACTIONS(159),
    [sym_quote4_prefix] = ACTIONS(162),
    [sym_quote5_prefix] = ACTIONS(165),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(168),
  },
  [10] = {
    [sym_carryover_tag] = STATE(56),
    [sym_quote6_prefix] = STATE(52),
    [sym_quote2] = STATE(7),
    [sym_quote3] = STATE(7),
    [sym_quote4] = STATE(7),
    [sym_quote5] = STATE(7),
    [sym_quote6] = STATE(7),
    [aux_sym_quote1_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(171),
    [sym_word] = ACTIONS(173),
    [sym_space] = ACTIONS(173),
    [sym_punctuation] = ACTIONS(173),
    [sym_line_break] = ACTIONS(171),
    [anon_sym_PLUS] = ACTIONS(175),
    [sym_quote1_prefix] = ACTIONS(171),
    [sym_quote2_prefix] = ACTIONS(178),
    [sym_quote3_prefix] = ACTIONS(181),
    [sym_quote4_prefix] = ACTIONS(184),
    [sym_quote5_prefix] = ACTIONS(187),
    [anon_sym_GT_GT_GT_GT_GT_GT] = ACTIONS(190),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(197), 1,
      anon_sym_PLUS,
    ACTIONS(200), 1,
      sym_quote3_prefix,
    ACTIONS(203), 1,
      sym_quote4_prefix,
    ACTIONS(206), 1,
      sym_quote5_prefix,
    ACTIONS(209), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(57), 1,
      sym_carryover_tag,
    ACTIONS(195), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(193), 4,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
    STATE(13), 5,
      sym_quote3,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote2_repeat1,
  [40] = 10,
    ACTIONS(216), 1,
      anon_sym_PLUS,
    ACTIONS(219), 1,
      sym_quote3_prefix,
    ACTIONS(222), 1,
      sym_quote4_prefix,
    ACTIONS(225), 1,
      sym_quote5_prefix,
    ACTIONS(228), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(57), 1,
      sym_carryover_tag,
    ACTIONS(214), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(212), 4,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
    STATE(15), 5,
      sym_quote3,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote2_repeat1,
  [80] = 10,
    ACTIONS(235), 1,
      anon_sym_PLUS,
    ACTIONS(238), 1,
      sym_quote3_prefix,
    ACTIONS(241), 1,
      sym_quote4_prefix,
    ACTIONS(244), 1,
      sym_quote5_prefix,
    ACTIONS(247), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(57), 1,
      sym_carryover_tag,
    ACTIONS(233), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(231), 4,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
    STATE(13), 5,
      sym_quote3,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote2_repeat1,
  [120] = 10,
    ACTIONS(254), 1,
      anon_sym_PLUS,
    ACTIONS(257), 1,
      sym_quote3_prefix,
    ACTIONS(260), 1,
      sym_quote4_prefix,
    ACTIONS(263), 1,
      sym_quote5_prefix,
    ACTIONS(266), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(57), 1,
      sym_carryover_tag,
    ACTIONS(252), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(250), 4,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
    STATE(11), 5,
      sym_quote3,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote2_repeat1,
  [160] = 10,
    ACTIONS(273), 1,
      anon_sym_PLUS,
    ACTIONS(276), 1,
      sym_quote3_prefix,
    ACTIONS(279), 1,
      sym_quote4_prefix,
    ACTIONS(282), 1,
      sym_quote5_prefix,
    ACTIONS(285), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(57), 1,
      sym_carryover_tag,
    ACTIONS(271), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(269), 4,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
    STATE(13), 5,
      sym_quote3,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote2_repeat1,
  [200] = 9,
    ACTIONS(292), 1,
      anon_sym_PLUS,
    ACTIONS(295), 1,
      sym_quote4_prefix,
    ACTIONS(298), 1,
      sym_quote5_prefix,
    ACTIONS(301), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(59), 1,
      sym_carryover_tag,
    ACTIONS(290), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    STATE(20), 4,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote3_repeat1,
    ACTIONS(288), 5,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
  [237] = 9,
    ACTIONS(308), 1,
      anon_sym_PLUS,
    ACTIONS(311), 1,
      sym_quote4_prefix,
    ACTIONS(314), 1,
      sym_quote5_prefix,
    ACTIONS(317), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(59), 1,
      sym_carryover_tag,
    ACTIONS(306), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    STATE(18), 4,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote3_repeat1,
    ACTIONS(304), 5,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
  [274] = 9,
    ACTIONS(324), 1,
      anon_sym_PLUS,
    ACTIONS(327), 1,
      sym_quote4_prefix,
    ACTIONS(330), 1,
      sym_quote5_prefix,
    ACTIONS(333), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(59), 1,
      sym_carryover_tag,
    ACTIONS(322), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    STATE(18), 4,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote3_repeat1,
    ACTIONS(320), 5,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
  [311] = 9,
    ACTIONS(340), 1,
      anon_sym_PLUS,
    ACTIONS(343), 1,
      sym_quote4_prefix,
    ACTIONS(346), 1,
      sym_quote5_prefix,
    ACTIONS(349), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(59), 1,
      sym_carryover_tag,
    ACTIONS(338), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    STATE(17), 4,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote3_repeat1,
    ACTIONS(336), 5,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
  [348] = 9,
    ACTIONS(356), 1,
      anon_sym_PLUS,
    ACTIONS(359), 1,
      sym_quote4_prefix,
    ACTIONS(362), 1,
      sym_quote5_prefix,
    ACTIONS(365), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(59), 1,
      sym_carryover_tag,
    ACTIONS(354), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    STATE(18), 4,
      sym_quote4,
      sym_quote5,
      sym_quote6,
      aux_sym_quote3_repeat1,
    ACTIONS(352), 5,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
  [385] = 8,
    ACTIONS(372), 1,
      anon_sym_PLUS,
    ACTIONS(375), 1,
      sym_quote5_prefix,
    ACTIONS(378), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(64), 1,
      sym_carryover_tag,
    ACTIONS(370), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    STATE(25), 3,
      sym_quote5,
      sym_quote6,
      aux_sym_quote4_repeat1,
    ACTIONS(368), 6,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
  [419] = 8,
    ACTIONS(385), 1,
      anon_sym_PLUS,
    ACTIONS(388), 1,
      sym_quote5_prefix,
    ACTIONS(391), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(64), 1,
      sym_carryover_tag,
    ACTIONS(383), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    STATE(25), 3,
      sym_quote5,
      sym_quote6,
      aux_sym_quote4_repeat1,
    ACTIONS(381), 6,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
  [453] = 8,
    ACTIONS(398), 1,
      anon_sym_PLUS,
    ACTIONS(401), 1,
      sym_quote5_prefix,
    ACTIONS(404), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(64), 1,
      sym_carryover_tag,
    ACTIONS(396), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    STATE(21), 3,
      sym_quote5,
      sym_quote6,
      aux_sym_quote4_repeat1,
    ACTIONS(394), 6,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
  [487] = 8,
    ACTIONS(411), 1,
      anon_sym_PLUS,
    ACTIONS(414), 1,
      sym_quote5_prefix,
    ACTIONS(417), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(64), 1,
      sym_carryover_tag,
    ACTIONS(409), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    STATE(22), 3,
      sym_quote5,
      sym_quote6,
      aux_sym_quote4_repeat1,
    ACTIONS(407), 6,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
  [521] = 8,
    ACTIONS(424), 1,
      anon_sym_PLUS,
    ACTIONS(427), 1,
      sym_quote5_prefix,
    ACTIONS(430), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(64), 1,
      sym_carryover_tag,
    ACTIONS(422), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    STATE(25), 3,
      sym_quote5,
      sym_quote6,
      aux_sym_quote4_repeat1,
    ACTIONS(420), 6,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
  [555] = 5,
    ACTIONS(438), 1,
      sym_line_break,
    STATE(26), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(435), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(433), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [582] = 7,
    ACTIONS(445), 1,
      anon_sym_PLUS,
    ACTIONS(448), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(65), 1,
      sym_carryover_tag,
    STATE(30), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(443), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(441), 7,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
  [613] = 7,
    ACTIONS(455), 1,
      anon_sym_PLUS,
    ACTIONS(458), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(65), 1,
      sym_carryover_tag,
    STATE(32), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(453), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(451), 7,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
  [644] = 5,
    ACTIONS(466), 1,
      sym_line_break,
    STATE(26), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(463), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(461), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [671] = 7,
    ACTIONS(473), 1,
      anon_sym_PLUS,
    ACTIONS(476), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(65), 1,
      sym_carryover_tag,
    STATE(31), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(471), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(469), 7,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
  [702] = 7,
    ACTIONS(483), 1,
      anon_sym_PLUS,
    ACTIONS(486), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(65), 1,
      sym_carryover_tag,
    STATE(31), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(481), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(479), 7,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
  [733] = 7,
    ACTIONS(493), 1,
      anon_sym_PLUS,
    ACTIONS(496), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(52), 1,
      sym_quote6_prefix,
    STATE(65), 1,
      sym_carryover_tag,
    STATE(31), 2,
      sym_quote6,
      aux_sym_quote5_repeat1,
    ACTIONS(491), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(489), 7,
      ts_builtin_sym_end,
      sym_line_break,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
  [764] = 3,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(501), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(499), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [785] = 3,
    STATE(34), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(505), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(503), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [806] = 3,
    STATE(38), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(510), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(508), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [826] = 3,
    STATE(35), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(514), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(512), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [846] = 3,
    STATE(39), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(518), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(516), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [866] = 3,
    STATE(38), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(522), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(520), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [886] = 3,
    STATE(38), 1,
      aux_sym_quote6_repeat1,
    ACTIONS(526), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(524), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [906] = 3,
    ACTIONS(532), 1,
      sym_line_break,
    ACTIONS(530), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(528), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [925] = 2,
    ACTIONS(537), 3,
      sym_word,
      sym_space,
      sym_punctuation,
    ACTIONS(535), 9,
      ts_builtin_sym_end,
      sym_line_break,
      anon_sym_PLUS,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [942] = 5,
    ACTIONS(539), 1,
      sym_line_break,
    STATE(12), 1,
      sym_paragraph,
    STATE(29), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(5), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [962] = 5,
    ACTIONS(539), 1,
      sym_line_break,
    STATE(14), 1,
      sym_paragraph,
    STATE(29), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(5), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [982] = 5,
    ACTIONS(539), 1,
      sym_line_break,
    STATE(19), 1,
      sym_paragraph,
    STATE(29), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(5), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [1002] = 5,
    ACTIONS(539), 1,
      sym_line_break,
    STATE(8), 1,
      sym_paragraph,
    STATE(29), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(5), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [1022] = 5,
    ACTIONS(539), 1,
      sym_line_break,
    STATE(24), 1,
      sym_paragraph,
    STATE(29), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(5), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [1042] = 5,
    ACTIONS(539), 1,
      sym_line_break,
    STATE(10), 1,
      sym_paragraph,
    STATE(29), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(5), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [1062] = 5,
    ACTIONS(539), 1,
      sym_line_break,
    STATE(27), 1,
      sym_paragraph,
    STATE(29), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(5), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [1082] = 5,
    ACTIONS(539), 1,
      sym_line_break,
    STATE(37), 1,
      sym_paragraph,
    STATE(29), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(5), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [1102] = 5,
    ACTIONS(539), 1,
      sym_line_break,
    STATE(28), 1,
      sym_paragraph,
    STATE(29), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(5), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [1122] = 5,
    ACTIONS(539), 1,
      sym_line_break,
    STATE(23), 1,
      sym_paragraph,
    STATE(29), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(5), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [1142] = 5,
    ACTIONS(539), 1,
      sym_line_break,
    STATE(36), 1,
      sym_paragraph,
    STATE(29), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(5), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [1162] = 5,
    ACTIONS(539), 1,
      sym_line_break,
    STATE(16), 1,
      sym_paragraph,
    STATE(29), 2,
      sym_paragraph_segment,
      aux_sym_paragraph_repeat1,
    STATE(33), 2,
      sym__paragraph_element,
      aux_sym_paragraph_segment_repeat1,
    ACTIONS(5), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [1182] = 7,
    ACTIONS(21), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    ACTIONS(541), 1,
      sym_quote1_prefix,
    ACTIONS(543), 1,
      sym_quote2_prefix,
    ACTIONS(545), 1,
      sym_quote3_prefix,
    ACTIONS(547), 1,
      sym_quote4_prefix,
    ACTIONS(549), 1,
      sym_quote5_prefix,
    STATE(49), 1,
      sym_quote6_prefix,
  [1204] = 1,
    ACTIONS(551), 6,
      sym_quote1_prefix,
      sym_quote2_prefix,
      sym_quote3_prefix,
      sym_quote4_prefix,
      sym_quote5_prefix,
      anon_sym_GT_GT_GT_GT_GT_GT,
  [1213] = 6,
    ACTIONS(21), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    ACTIONS(543), 1,
      sym_quote2_prefix,
    ACTIONS(545), 1,
      sym_quote3_prefix,
    ACTIONS(547), 1,
      sym_quote4_prefix,
    ACTIONS(549), 1,
      sym_quote5_prefix,
    STATE(49), 1,
      sym_quote6_prefix,
  [1232] = 5,
    ACTIONS(21), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    ACTIONS(545), 1,
      sym_quote3_prefix,
    ACTIONS(547), 1,
      sym_quote4_prefix,
    ACTIONS(549), 1,
      sym_quote5_prefix,
    STATE(49), 1,
      sym_quote6_prefix,
  [1248] = 2,
    ACTIONS(555), 1,
      sym_line_break,
    ACTIONS(553), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [1257] = 4,
    ACTIONS(21), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    ACTIONS(547), 1,
      sym_quote4_prefix,
    ACTIONS(549), 1,
      sym_quote5_prefix,
    STATE(49), 1,
      sym_quote6_prefix,
  [1270] = 2,
    ACTIONS(559), 1,
      sym_line_break,
    ACTIONS(557), 3,
      sym_word,
      sym_space,
      sym_punctuation,
  [1279] = 3,
    ACTIONS(561), 1,
      anon_sym_GT,
    ACTIONS(563), 1,
      anon_sym_,
    STATE(63), 1,
      aux_sym_quote6_prefix_repeat1,
  [1289] = 3,
    ACTIONS(565), 1,
      anon_sym_GT,
    ACTIONS(567), 1,
      anon_sym_,
    STATE(61), 1,
      aux_sym_quote6_prefix_repeat1,
  [1299] = 3,
    ACTIONS(569), 1,
      anon_sym_GT,
    ACTIONS(572), 1,
      anon_sym_,
    STATE(63), 1,
      aux_sym_quote6_prefix_repeat1,
  [1309] = 3,
    ACTIONS(21), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    ACTIONS(549), 1,
      sym_quote5_prefix,
    STATE(49), 1,
      sym_quote6_prefix,
  [1319] = 2,
    ACTIONS(21), 1,
      anon_sym_GT_GT_GT_GT_GT_GT,
    STATE(49), 1,
      sym_quote6_prefix,
  [1326] = 1,
    ACTIONS(574), 1,
      ts_builtin_sym_end,
  [1330] = 1,
    ACTIONS(576), 1,
      sym_line_break,
  [1334] = 1,
    ACTIONS(578), 1,
      sym_word,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 40,
  [SMALL_STATE(13)] = 80,
  [SMALL_STATE(14)] = 120,
  [SMALL_STATE(15)] = 160,
  [SMALL_STATE(16)] = 200,
  [SMALL_STATE(17)] = 237,
  [SMALL_STATE(18)] = 274,
  [SMALL_STATE(19)] = 311,
  [SMALL_STATE(20)] = 348,
  [SMALL_STATE(21)] = 385,
  [SMALL_STATE(22)] = 419,
  [SMALL_STATE(23)] = 453,
  [SMALL_STATE(24)] = 487,
  [SMALL_STATE(25)] = 521,
  [SMALL_STATE(26)] = 555,
  [SMALL_STATE(27)] = 582,
  [SMALL_STATE(28)] = 613,
  [SMALL_STATE(29)] = 644,
  [SMALL_STATE(30)] = 671,
  [SMALL_STATE(31)] = 702,
  [SMALL_STATE(32)] = 733,
  [SMALL_STATE(33)] = 764,
  [SMALL_STATE(34)] = 785,
  [SMALL_STATE(35)] = 806,
  [SMALL_STATE(36)] = 826,
  [SMALL_STATE(37)] = 846,
  [SMALL_STATE(38)] = 866,
  [SMALL_STATE(39)] = 886,
  [SMALL_STATE(40)] = 906,
  [SMALL_STATE(41)] = 925,
  [SMALL_STATE(42)] = 942,
  [SMALL_STATE(43)] = 962,
  [SMALL_STATE(44)] = 982,
  [SMALL_STATE(45)] = 1002,
  [SMALL_STATE(46)] = 1022,
  [SMALL_STATE(47)] = 1042,
  [SMALL_STATE(48)] = 1062,
  [SMALL_STATE(49)] = 1082,
  [SMALL_STATE(50)] = 1102,
  [SMALL_STATE(51)] = 1122,
  [SMALL_STATE(52)] = 1142,
  [SMALL_STATE(53)] = 1162,
  [SMALL_STATE(54)] = 1182,
  [SMALL_STATE(55)] = 1204,
  [SMALL_STATE(56)] = 1213,
  [SMALL_STATE(57)] = 1232,
  [SMALL_STATE(58)] = 1248,
  [SMALL_STATE(59)] = 1257,
  [SMALL_STATE(60)] = 1270,
  [SMALL_STATE(61)] = 1279,
  [SMALL_STATE(62)] = 1289,
  [SMALL_STATE(63)] = 1299,
  [SMALL_STATE(64)] = 1309,
  [SMALL_STATE(65)] = 1319,
  [SMALL_STATE(66)] = 1326,
  [SMALL_STATE(67)] = 1330,
  [SMALL_STATE(68)] = 1334,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(33),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(40),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(68),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(45),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(43),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(44),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(46),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(48),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(62),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote_repeat1, 2),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(68),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(45),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(43),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(44),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(46),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(48),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2), SHIFT_REPEAT(62),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 1),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 1),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote1, 3, .production_id = 1),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 1), SHIFT(68),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 1), SHIFT(43),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 1), SHIFT(44),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 1), SHIFT(46),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 1), SHIFT(48),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 1), SHIFT(62),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote1, 4, .production_id = 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote1, 4, .production_id = 3),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4, .production_id = 3), SHIFT(68),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4, .production_id = 3), SHIFT(43),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4, .production_id = 3), SHIFT(44),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4, .production_id = 3), SHIFT(46),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4, .production_id = 3), SHIFT(48),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 4, .production_id = 3), SHIFT(62),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote1, 2, .production_id = 1),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote1, 2, .production_id = 1),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2, .production_id = 1), SHIFT(68),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2, .production_id = 1), SHIFT(43),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2, .production_id = 1), SHIFT(44),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2, .production_id = 1), SHIFT(46),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2, .production_id = 1), SHIFT(48),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 2, .production_id = 1), SHIFT(62),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote1_repeat1, 2),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(68),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(43),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(44),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(46),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(48),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote1_repeat1, 2), SHIFT_REPEAT(62),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 3),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote1, 3, .production_id = 3),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 3), SHIFT(68),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 3), SHIFT(43),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 3), SHIFT(44),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 3), SHIFT(46),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 3), SHIFT(48),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote1, 3, .production_id = 3), SHIFT(62),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote2, 3, .production_id = 1),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote2, 3, .production_id = 1),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3, .production_id = 1), SHIFT(68),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3, .production_id = 1), SHIFT(44),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3, .production_id = 1), SHIFT(46),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3, .production_id = 1), SHIFT(48),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3, .production_id = 1), SHIFT(62),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote2, 3, .production_id = 3),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote2, 3, .production_id = 3),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3, .production_id = 3), SHIFT(68),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3, .production_id = 3), SHIFT(44),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3, .production_id = 3), SHIFT(46),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3, .production_id = 3), SHIFT(48),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 3, .production_id = 3), SHIFT(62),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote2_repeat1, 2),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(68),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(44),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(46),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(48),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote2_repeat1, 2), SHIFT_REPEAT(62),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote2, 2, .production_id = 1),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote2, 2, .production_id = 1),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2, .production_id = 1), SHIFT(68),
  [257] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2, .production_id = 1), SHIFT(44),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2, .production_id = 1), SHIFT(46),
  [263] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2, .production_id = 1), SHIFT(48),
  [266] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 2, .production_id = 1), SHIFT(62),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote2, 4, .production_id = 3),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote2, 4, .production_id = 3),
  [273] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4, .production_id = 3), SHIFT(68),
  [276] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4, .production_id = 3), SHIFT(44),
  [279] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4, .production_id = 3), SHIFT(46),
  [282] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4, .production_id = 3), SHIFT(48),
  [285] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote2, 4, .production_id = 3), SHIFT(62),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote3, 3, .production_id = 3),
  [290] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote3, 3, .production_id = 3),
  [292] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3, .production_id = 3), SHIFT(68),
  [295] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3, .production_id = 3), SHIFT(46),
  [298] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3, .production_id = 3), SHIFT(48),
  [301] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3, .production_id = 3), SHIFT(62),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote3, 3, .production_id = 1),
  [306] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote3, 3, .production_id = 1),
  [308] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3, .production_id = 1), SHIFT(68),
  [311] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3, .production_id = 1), SHIFT(46),
  [314] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3, .production_id = 1), SHIFT(48),
  [317] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 3, .production_id = 1), SHIFT(62),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2),
  [322] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote3_repeat1, 2),
  [324] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2), SHIFT_REPEAT(68),
  [327] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2), SHIFT_REPEAT(46),
  [330] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2), SHIFT_REPEAT(48),
  [333] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote3_repeat1, 2), SHIFT_REPEAT(62),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote3, 2, .production_id = 1),
  [338] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote3, 2, .production_id = 1),
  [340] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 2, .production_id = 1), SHIFT(68),
  [343] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 2, .production_id = 1), SHIFT(46),
  [346] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 2, .production_id = 1), SHIFT(48),
  [349] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 2, .production_id = 1), SHIFT(62),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote3, 4, .production_id = 3),
  [354] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote3, 4, .production_id = 3),
  [356] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 4, .production_id = 3), SHIFT(68),
  [359] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 4, .production_id = 3), SHIFT(46),
  [362] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 4, .production_id = 3), SHIFT(48),
  [365] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote3, 4, .production_id = 3), SHIFT(62),
  [368] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote4, 4, .production_id = 3),
  [370] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote4, 4, .production_id = 3),
  [372] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 4, .production_id = 3), SHIFT(68),
  [375] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 4, .production_id = 3), SHIFT(48),
  [378] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 4, .production_id = 3), SHIFT(62),
  [381] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote4, 3, .production_id = 1),
  [383] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote4, 3, .production_id = 1),
  [385] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 3, .production_id = 1), SHIFT(68),
  [388] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 3, .production_id = 1), SHIFT(48),
  [391] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 3, .production_id = 1), SHIFT(62),
  [394] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote4, 3, .production_id = 3),
  [396] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote4, 3, .production_id = 3),
  [398] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 3, .production_id = 3), SHIFT(68),
  [401] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 3, .production_id = 3), SHIFT(48),
  [404] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 3, .production_id = 3), SHIFT(62),
  [407] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote4, 2, .production_id = 1),
  [409] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote4, 2, .production_id = 1),
  [411] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 2, .production_id = 1), SHIFT(68),
  [414] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 2, .production_id = 1), SHIFT(48),
  [417] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote4, 2, .production_id = 1), SHIFT(62),
  [420] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote4_repeat1, 2),
  [422] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote4_repeat1, 2),
  [424] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote4_repeat1, 2), SHIFT_REPEAT(68),
  [427] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote4_repeat1, 2), SHIFT_REPEAT(48),
  [430] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote4_repeat1, 2), SHIFT_REPEAT(62),
  [433] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [435] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(33),
  [438] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(26),
  [441] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote5, 2, .production_id = 1),
  [443] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote5, 2, .production_id = 1),
  [445] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 2, .production_id = 1), SHIFT(68),
  [448] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 2, .production_id = 1), SHIFT(62),
  [451] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote5, 3, .production_id = 3),
  [453] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote5, 3, .production_id = 3),
  [455] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 3, .production_id = 3), SHIFT(68),
  [458] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 3, .production_id = 3), SHIFT(62),
  [461] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [463] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_paragraph, 1), SHIFT(33),
  [466] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_paragraph, 1), SHIFT(26),
  [469] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote5, 3, .production_id = 1),
  [471] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote5, 3, .production_id = 1),
  [473] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 3, .production_id = 1), SHIFT(68),
  [476] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 3, .production_id = 1), SHIFT(62),
  [479] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote5_repeat1, 2),
  [481] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote5_repeat1, 2),
  [483] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote5_repeat1, 2), SHIFT_REPEAT(68),
  [486] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote5_repeat1, 2), SHIFT_REPEAT(62),
  [489] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote5, 4, .production_id = 3),
  [491] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote5, 4, .production_id = 3),
  [493] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 4, .production_id = 3), SHIFT(68),
  [496] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quote5, 4, .production_id = 3), SHIFT(62),
  [499] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph_segment, 1),
  [501] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [503] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_segment_repeat1, 2),
  [505] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_segment_repeat1, 2), SHIFT_REPEAT(34),
  [508] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote6, 3, .production_id = 1),
  [510] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote6, 3, .production_id = 1),
  [512] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote6, 2, .production_id = 1),
  [514] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote6, 2, .production_id = 1),
  [516] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote6, 3, .production_id = 3),
  [518] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote6, 3, .production_id = 3),
  [520] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote6_repeat1, 2),
  [522] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote6_repeat1, 2),
  [524] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote6, 4, .production_id = 3),
  [526] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote6, 4, .production_id = 3),
  [528] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 1),
  [530] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 1),
  [532] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 1), SHIFT(41),
  [535] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph_break, 2, .dynamic_precedence = 2),
  [537] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph_break, 2, .dynamic_precedence = 2),
  [539] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [541] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [543] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [545] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [547] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [549] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [551] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_carryover_tag, 3, .production_id = 2),
  [553] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote6_prefix, 3),
  [555] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote6_prefix, 3),
  [557] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote6_prefix, 2),
  [559] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote6_prefix, 2),
  [561] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [563] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [565] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [567] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [569] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote6_prefix_repeat1, 2), SHIFT_REPEAT(63),
  [572] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote6_prefix_repeat1, 2),
  [574] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [576] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [578] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_norg2(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
